//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "AndroidAppApplication.h"
#include "DaggerMembersInjector.h"
#include "J2ObjC_source.h"
#include "PDDatabaseHelperTest.h"
#include "PDDatabaseHelperTest_MembersInjector.h"
#include "java/lang/NullPointerException.h"
#include "javax/inject/Provider.h"

@interface PDDatabaseHelperTest_MembersInjector () {
 @public
  id<JavaxInjectProvider> applicationProvider_;
}

@end

J2OBJC_FIELD_SETTER(PDDatabaseHelperTest_MembersInjector, applicationProvider_, id<JavaxInjectProvider>)

@implementation PDDatabaseHelperTest_MembersInjector

- (instancetype)initWithJavaxInjectProvider:(id<JavaxInjectProvider>)applicationProvider {
  PDDatabaseHelperTest_MembersInjector_initWithJavaxInjectProvider_(self, applicationProvider);
  return self;
}

+ (id<DaggerMembersInjector>)createWithJavaxInjectProvider:(id<JavaxInjectProvider>)applicationProvider {
  return PDDatabaseHelperTest_MembersInjector_createWithJavaxInjectProvider_(applicationProvider);
}

- (void)injectMembersWithId:(PDDatabaseHelperTest *)instance {
  if (instance == nil) {
    @throw create_JavaLangNullPointerException_initWithNSString_(@"Cannot inject members into a null reference");
  }
  JreStrongAssign(&instance->application_, [((id<JavaxInjectProvider>) nil_chk(applicationProvider_)) get]);
}

+ (void)injectApplicationWithPDDatabaseHelperTest:(PDDatabaseHelperTest *)instance
                          withJavaxInjectProvider:(id<JavaxInjectProvider>)applicationProvider {
  PDDatabaseHelperTest_MembersInjector_injectApplicationWithPDDatabaseHelperTest_withJavaxInjectProvider_(instance, applicationProvider);
}

- (void)dealloc {
  RELEASE_(applicationProvider_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, 1, -1, -1 },
    { NULL, "LDaggerMembersInjector;", 0x9, 2, 0, -1, 3, -1, -1 },
    { NULL, "V", 0x1, 4, 5, -1, -1, -1, -1 },
    { NULL, "V", 0x9, 6, 7, -1, 8, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithJavaxInjectProvider:);
  methods[1].selector = @selector(createWithJavaxInjectProvider:);
  methods[2].selector = @selector(injectMembersWithId:);
  methods[3].selector = @selector(injectApplicationWithPDDatabaseHelperTest:withJavaxInjectProvider:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "applicationProvider_", "LJavaxInjectProvider;", .constantValue.asLong = 0, 0x12, -1, -1, 9, -1 },
  };
  static const void *ptrTable[] = { "LJavaxInjectProvider;", "(Ljavax/inject/Provider<Landroid/app/Application;>;)V", "create", "(Ljavax/inject/Provider<Landroid/app/Application;>;)Ldagger/MembersInjector<Lcom/kgalligan/partyclicker/data/DatabaseHelperTest;>;", "injectMembers", "LPDDatabaseHelperTest;", "injectApplication", "LPDDatabaseHelperTest;LJavaxInjectProvider;", "(Lcom/kgalligan/partyclicker/data/DatabaseHelperTest;Ljavax/inject/Provider<Landroid/app/Application;>;)V", "Ljavax/inject/Provider<Landroid/app/Application;>;", "Ljava/lang/Object;Ldagger/MembersInjector<Lcom/kgalligan/partyclicker/data/DatabaseHelperTest;>;" };
  static const J2ObjcClassInfo _PDDatabaseHelperTest_MembersInjector = { "DatabaseHelperTest_MembersInjector", "com.kgalligan.partyclicker.data", ptrTable, methods, fields, 7, 0x11, 4, 1, -1, -1, -1, 10, -1 };
  return &_PDDatabaseHelperTest_MembersInjector;
}

@end

void PDDatabaseHelperTest_MembersInjector_initWithJavaxInjectProvider_(PDDatabaseHelperTest_MembersInjector *self, id<JavaxInjectProvider> applicationProvider) {
  NSObject_init(self);
  JreAssert((applicationProvider != nil), (@"com/kgalligan/partyclicker/data/DatabaseHelperTest_MembersInjector.java:17 condition failed: assert applicationProvider != null;"));
  JreStrongAssign(&self->applicationProvider_, applicationProvider);
}

PDDatabaseHelperTest_MembersInjector *new_PDDatabaseHelperTest_MembersInjector_initWithJavaxInjectProvider_(id<JavaxInjectProvider> applicationProvider) {
  J2OBJC_NEW_IMPL(PDDatabaseHelperTest_MembersInjector, initWithJavaxInjectProvider_, applicationProvider)
}

PDDatabaseHelperTest_MembersInjector *create_PDDatabaseHelperTest_MembersInjector_initWithJavaxInjectProvider_(id<JavaxInjectProvider> applicationProvider) {
  J2OBJC_CREATE_IMPL(PDDatabaseHelperTest_MembersInjector, initWithJavaxInjectProvider_, applicationProvider)
}

id<DaggerMembersInjector> PDDatabaseHelperTest_MembersInjector_createWithJavaxInjectProvider_(id<JavaxInjectProvider> applicationProvider) {
  PDDatabaseHelperTest_MembersInjector_initialize();
  return create_PDDatabaseHelperTest_MembersInjector_initWithJavaxInjectProvider_(applicationProvider);
}

void PDDatabaseHelperTest_MembersInjector_injectApplicationWithPDDatabaseHelperTest_withJavaxInjectProvider_(PDDatabaseHelperTest *instance, id<JavaxInjectProvider> applicationProvider) {
  PDDatabaseHelperTest_MembersInjector_initialize();
  JreStrongAssign(&((PDDatabaseHelperTest *) nil_chk(instance))->application_, [((id<JavaxInjectProvider>) nil_chk(applicationProvider)) get]);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(PDDatabaseHelperTest_MembersInjector)
