//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "DaggerMembersInjector.h"
#include "J2ObjC_source.h"
#include "PDDataProvider.h"
#include "PDModPersonTaskTest.h"
#include "PDModPersonTaskTest_MembersInjector.h"
#include "java/lang/NullPointerException.h"
#include "javax/inject/Provider.h"

@interface PDModPersonTaskTest_MembersInjector () {
 @public
  id<JavaxInjectProvider> dataProvider_;
}

@end

J2OBJC_FIELD_SETTER(PDModPersonTaskTest_MembersInjector, dataProvider_, id<JavaxInjectProvider>)

@implementation PDModPersonTaskTest_MembersInjector

- (instancetype)initWithJavaxInjectProvider:(id<JavaxInjectProvider>)dataProvider {
  PDModPersonTaskTest_MembersInjector_initWithJavaxInjectProvider_(self, dataProvider);
  return self;
}

+ (id<DaggerMembersInjector>)createWithJavaxInjectProvider:(id<JavaxInjectProvider>)dataProvider {
  return PDModPersonTaskTest_MembersInjector_createWithJavaxInjectProvider_(dataProvider);
}

- (void)injectMembersWithId:(PDModPersonTaskTest *)instance {
  if (instance == nil) {
    @throw create_JavaLangNullPointerException_initWithNSString_(@"Cannot inject members into a null reference");
  }
  JreStrongAssign(&instance->dataProvider_, [((id<JavaxInjectProvider>) nil_chk(dataProvider_)) get]);
}

+ (void)injectDataProviderWithPDModPersonTaskTest:(PDModPersonTaskTest *)instance
                          withJavaxInjectProvider:(id<JavaxInjectProvider>)dataProvider {
  PDModPersonTaskTest_MembersInjector_injectDataProviderWithPDModPersonTaskTest_withJavaxInjectProvider_(instance, dataProvider);
}

- (void)dealloc {
  RELEASE_(dataProvider_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, 1, -1, -1 },
    { NULL, "LDaggerMembersInjector;", 0x9, 2, 0, -1, 3, -1, -1 },
    { NULL, "V", 0x1, 4, 5, -1, -1, -1, -1 },
    { NULL, "V", 0x9, 6, 7, -1, 8, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithJavaxInjectProvider:);
  methods[1].selector = @selector(createWithJavaxInjectProvider:);
  methods[2].selector = @selector(injectMembersWithId:);
  methods[3].selector = @selector(injectDataProviderWithPDModPersonTaskTest:withJavaxInjectProvider:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "dataProvider_", "LJavaxInjectProvider;", .constantValue.asLong = 0, 0x12, -1, -1, 9, -1 },
  };
  static const void *ptrTable[] = { "LJavaxInjectProvider;", "(Ljavax/inject/Provider<Lcom/kgalligan/partyclicker/data/DataProvider;>;)V", "create", "(Ljavax/inject/Provider<Lcom/kgalligan/partyclicker/data/DataProvider;>;)Ldagger/MembersInjector<Lcom/kgalligan/partyclicker/data/ModPersonTaskTest;>;", "injectMembers", "LPDModPersonTaskTest;", "injectDataProvider", "LPDModPersonTaskTest;LJavaxInjectProvider;", "(Lcom/kgalligan/partyclicker/data/ModPersonTaskTest;Ljavax/inject/Provider<Lcom/kgalligan/partyclicker/data/DataProvider;>;)V", "Ljavax/inject/Provider<Lcom/kgalligan/partyclicker/data/DataProvider;>;", "Ljava/lang/Object;Ldagger/MembersInjector<Lcom/kgalligan/partyclicker/data/ModPersonTaskTest;>;" };
  static const J2ObjcClassInfo _PDModPersonTaskTest_MembersInjector = { "ModPersonTaskTest_MembersInjector", "com.kgalligan.partyclicker.data", ptrTable, methods, fields, 7, 0x11, 4, 1, -1, -1, -1, 10, -1 };
  return &_PDModPersonTaskTest_MembersInjector;
}

@end

void PDModPersonTaskTest_MembersInjector_initWithJavaxInjectProvider_(PDModPersonTaskTest_MembersInjector *self, id<JavaxInjectProvider> dataProvider) {
  NSObject_init(self);
  JreAssert((dataProvider != nil), (@"com/kgalligan/partyclicker/data/ModPersonTaskTest_MembersInjector.java:15 condition failed: assert dataProvider != null;"));
  JreStrongAssign(&self->dataProvider_, dataProvider);
}

PDModPersonTaskTest_MembersInjector *new_PDModPersonTaskTest_MembersInjector_initWithJavaxInjectProvider_(id<JavaxInjectProvider> dataProvider) {
  J2OBJC_NEW_IMPL(PDModPersonTaskTest_MembersInjector, initWithJavaxInjectProvider_, dataProvider)
}

PDModPersonTaskTest_MembersInjector *create_PDModPersonTaskTest_MembersInjector_initWithJavaxInjectProvider_(id<JavaxInjectProvider> dataProvider) {
  J2OBJC_CREATE_IMPL(PDModPersonTaskTest_MembersInjector, initWithJavaxInjectProvider_, dataProvider)
}

id<DaggerMembersInjector> PDModPersonTaskTest_MembersInjector_createWithJavaxInjectProvider_(id<JavaxInjectProvider> dataProvider) {
  PDModPersonTaskTest_MembersInjector_initialize();
  return create_PDModPersonTaskTest_MembersInjector_initWithJavaxInjectProvider_(dataProvider);
}

void PDModPersonTaskTest_MembersInjector_injectDataProviderWithPDModPersonTaskTest_withJavaxInjectProvider_(PDModPersonTaskTest *instance, id<JavaxInjectProvider> dataProvider) {
  PDModPersonTaskTest_MembersInjector_initialize();
  JreStrongAssign(&((PDModPersonTaskTest *) nil_chk(instance))->dataProvider_, [((id<JavaxInjectProvider>) nil_chk(dataProvider)) get]);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(PDModPersonTaskTest_MembersInjector)
