//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_PPCrashReporterTest")
#ifdef RESTRICT_PPCrashReporterTest
#define INCLUDE_ALL_PPCrashReporterTest 0
#else
#define INCLUDE_ALL_PPCrashReporterTest 1
#endif
#undef RESTRICT_PPCrashReporterTest

#if !defined (PPCrashReporterTest_) && (INCLUDE_ALL_PPCrashReporterTest || defined(INCLUDE_PPCrashReporterTest))
#define PPCrashReporterTest_

@interface PPCrashReporterTest : NSObject

#pragma mark Public

- (instancetype)init;

- (void)logTest;

- (void)reportTest;

- (void)setUp;

@end

J2OBJC_EMPTY_STATIC_INIT(PPCrashReporterTest)

FOUNDATION_EXPORT void PPCrashReporterTest_init(PPCrashReporterTest *self);

FOUNDATION_EXPORT PPCrashReporterTest *new_PPCrashReporterTest_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT PPCrashReporterTest *create_PPCrashReporterTest_init();

J2OBJC_TYPE_LITERAL_HEADER(PPCrashReporterTest)

@compatibility_alias ComKgalliganPartyclickerPresenterCrashReporterTest PPCrashReporterTest;

#endif

#pragma pop_macro("INCLUDE_ALL_PPCrashReporterTest")
