//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_PPPartyPresenterTest")
#ifdef RESTRICT_PPPartyPresenterTest
#define INCLUDE_ALL_PPPartyPresenterTest 0
#else
#define INCLUDE_ALL_PPPartyPresenterTest 1
#endif
#undef RESTRICT_PPPartyPresenterTest

#if !defined (PPPartyPresenterTest_) && (INCLUDE_ALL_PPPartyPresenterTest || defined(INCLUDE_PPPartyPresenterTest))
#define PPPartyPresenterTest_

@protocol PDDataProvider;

@interface PPPartyPresenterTest : NSObject {
 @public
  id<PDDataProvider> dataProvider_;
}

#pragma mark Public

- (instancetype)init;

- (void)addPerson;

- (void)getParty;

- (void)getPartyCount;

- (void)init__ OBJC_METHOD_FAMILY_NONE;

- (void)removePerson;

- (void)setUp;

@end

J2OBJC_EMPTY_STATIC_INIT(PPPartyPresenterTest)

J2OBJC_FIELD_SETTER(PPPartyPresenterTest, dataProvider_, id<PDDataProvider>)

FOUNDATION_EXPORT void PPPartyPresenterTest_init(PPPartyPresenterTest *self);

FOUNDATION_EXPORT PPPartyPresenterTest *new_PPPartyPresenterTest_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT PPPartyPresenterTest *create_PPPartyPresenterTest_init();

J2OBJC_TYPE_LITERAL_HEADER(PPPartyPresenterTest)

@compatibility_alias ComKgalliganPartyclickerPresenterPartyPresenterTest PPPartyPresenterTest;

#endif

#pragma pop_macro("INCLUDE_ALL_PPPartyPresenterTest")
