//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "PDDataProvider.h"
#include "PDParty.h"
#include "PDPerson.h"
#include "PPPartyListPresenter.h"
#include "PPPartyListPresenterTest.h"
#include "PTDaggerTestNoContextComponent.h"
#include "PTTestNoContextComponent.h"
#include "PTTestNoContextModule.h"
#include "java/lang/annotation/Annotation.h"
#include "java/util/List.h"
#include "javax/inject/Inject.h"
#include "org/junit/Assert.h"
#include "org/junit/Before.h"
#include "org/junit/Test.h"
#include "org/mockito/ArgumentCaptor.h"
#include "org/mockito/Matchers.h"
#include "org/mockito/Mockito.h"

@interface PPPartyListPresenterTest () {
 @public
  PPPartyListPresenter *partyListPresenter_;
  id<PPPartyListPresenter_UiInterface> uiInterface_;
}

@end

J2OBJC_FIELD_SETTER(PPPartyListPresenterTest, partyListPresenter_, PPPartyListPresenter *)
J2OBJC_FIELD_SETTER(PPPartyListPresenterTest, uiInterface_, id<PPPartyListPresenter_UiInterface>)

__attribute__((unused)) static IOSObjectArray *PPPartyListPresenterTest__Annotations$0();

__attribute__((unused)) static IOSObjectArray *PPPartyListPresenterTest__Annotations$1();

__attribute__((unused)) static IOSObjectArray *PPPartyListPresenterTest__Annotations$2();

__attribute__((unused)) static IOSObjectArray *PPPartyListPresenterTest__Annotations$3();

__attribute__((unused)) static IOSObjectArray *PPPartyListPresenterTest__Annotations$4();

__attribute__((unused)) static IOSObjectArray *PPPartyListPresenterTest__Annotations$5();

__attribute__((unused)) static IOSObjectArray *PPPartyListPresenterTest__Annotations$6();

__attribute__((unused)) static IOSObjectArray *PPPartyListPresenterTest__Annotations$7();

@implementation PPPartyListPresenterTest

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  PPPartyListPresenterTest_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (void)setUp {
  id<PTTestNoContextComponent> testComponent = [((PTDaggerTestNoContextComponent_Builder *) nil_chk([((PTDaggerTestNoContextComponent_Builder *) nil_chk(PTDaggerTestNoContextComponent_builder())) testNoContextModuleWithPTTestNoContextModule:create_PTTestNoContextModule_init()])) build];
  [((id<PTTestNoContextComponent>) nil_chk(testComponent)) injectWithPPPartyListPresenterTest:self];
  JreStrongAssignAndConsume(&partyListPresenter_, new_PPPartyListPresenter_init());
  [testComponent injectWithPPPartyListPresenter:partyListPresenter_];
  JreStrongAssign(&uiInterface_, OrgMockitoMockito_mockWithIOSClass_(PPPartyListPresenter_UiInterface_class_()));
  [((PPPartyListPresenter *) nil_chk(partyListPresenter_)) applyUiInterfaceWithPPPartyListPresenter_UiInterface:uiInterface_];
}

- (void)callRefreshPartyList {
  [((PPPartyListPresenter *) nil_chk(partyListPresenter_)) callRefreshPartyList];
  [((id<PPPartyListPresenter_UiInterface>) nil_chk(OrgMockitoMockito_verifyWithId_(uiInterface_))) refreshPartyListWithJavaUtilList:OrgMockitoMatchers_anyWithIOSClass_(JavaUtilList_class_())];
}

- (void)callParty {
  PDParty *hello = [((id<PDDataProvider>) nil_chk(dataProvider_)) createPartyWithNSString:@"hello"];
  [((PPPartyListPresenter *) nil_chk(partyListPresenter_)) callPartyWithInt:[((PDParty *) nil_chk(hello)) getId]];
  [((id<PPPartyListPresenter_UiInterface>) nil_chk(OrgMockitoMockito_verifyWithId_(uiInterface_))) showPartyWithPDParty:hello];
}

- (void)createParty {
  OrgMockitoArgumentCaptor *captor = OrgMockitoArgumentCaptor_forClassWithIOSClass_(PDParty_class_());
  [((id<PDDataProvider>) nil_chk(dataProvider_)) createPartyWithNSString:@"not a stone groove"];
  [((PPPartyListPresenter *) nil_chk(partyListPresenter_)) createPartyWithNSString:@"a stone groove"];
  [((id<PPPartyListPresenter_UiInterface>) nil_chk(OrgMockitoMockito_verifyWithId_(uiInterface_))) showPartyWithPDParty:[((OrgMockitoArgumentCaptor *) nil_chk(captor)) capture]];
  OrgJunitAssert_assertEqualsWithId_withId_([((PDParty *) nil_chk([captor getValue])) getName], @"a stone groove");
}

- (void)deleteParty {
  [((id<PDDataProvider>) nil_chk(dataProvider_)) createPartyWithNSString:@"a"];
  [((id<PDDataProvider>) nil_chk(dataProvider_)) createPartyWithNSString:@"b"];
  PDParty *party = [((id<PDDataProvider>) nil_chk(dataProvider_)) createPartyWithNSString:@"c"];
  [((id<PDDataProvider>) nil_chk(dataProvider_)) createPartyWithNSString:@"d"];
  [((PPPartyListPresenter *) nil_chk(partyListPresenter_)) deletePartyWithInt:[((PDParty *) nil_chk(party)) getId]];
  OrgJunitAssert_assertEqualsWithLong_withLong_(3, [((id<JavaUtilList>) nil_chk([((id<PDDataProvider>) nil_chk(dataProvider_)) allParties])) size]);
}

- (void)countPeople {
  [((id<PDDataProvider>) nil_chk(dataProvider_)) createPartyWithNSString:@"a"];
  [((id<PDDataProvider>) nil_chk(dataProvider_)) createPartyWithNSString:@"b"];
  PDParty *party = [((id<PDDataProvider>) nil_chk(dataProvider_)) createPartyWithNSString:@"c"];
  [((id<PDDataProvider>) nil_chk(dataProvider_)) createPartyWithNSString:@"d"];
  [((id<PDDataProvider>) nil_chk(dataProvider_)) addPersonWithPDParty:party withBoolean:true];
  [((id<PDDataProvider>) nil_chk(dataProvider_)) addPersonWithPDParty:party withBoolean:true];
  [((id<PDDataProvider>) nil_chk(dataProvider_)) addPersonWithPDParty:party withBoolean:true];
  [((id<PDDataProvider>) nil_chk(dataProvider_)) addPersonWithPDParty:party withBoolean:false];
  [((id<PDDataProvider>) nil_chk(dataProvider_)) addPersonWithPDParty:party withBoolean:true];
  jint countPeople = [((PPPartyListPresenter *) nil_chk(partyListPresenter_)) countPeopleWithPDParty:party];
  OrgJunitAssert_assertEqualsWithLong_withLong_(3, countPeople);
}

- (void)allPeople {
  PDParty *party = [((id<PDDataProvider>) nil_chk(dataProvider_)) createPartyWithNSString:@"on the patio"];
  [((id<PDDataProvider>) nil_chk(dataProvider_)) addPersonWithPDParty:party withBoolean:true];
  [((id<PDDataProvider>) nil_chk(dataProvider_)) addPersonWithPDParty:party withBoolean:true];
  [((id<PDDataProvider>) nil_chk(dataProvider_)) addPersonWithPDParty:party withBoolean:true];
  [((id<PDDataProvider>) nil_chk(dataProvider_)) addPersonWithPDParty:party withBoolean:false];
  [((id<PDDataProvider>) nil_chk(dataProvider_)) addPersonWithPDParty:party withBoolean:true];
  id<JavaUtilList> personList = [((PPPartyListPresenter *) nil_chk(partyListPresenter_)) allPeopleWithPDParty:party];
  id<JavaUtilList> memPersonLIst = [((id<PDDataProvider>) nil_chk(dataProvider_)) allPeopleForPartyWithPDParty:party];
  for (PDPerson * __strong person in nil_chk(personList)) {
    jboolean found = true;
    for (PDPerson * __strong memPerson in nil_chk(memPersonLIst)) {
      if ([((PDPerson *) nil_chk(person)) getId] == [((PDPerson *) nil_chk(memPerson)) getId]) {
        found = true;
        break;
      }
    }
    OrgJunitAssert_assertTrueWithBoolean_(found);
  }
}

- (void)dealloc {
  RELEASE_(dataProvider_);
  RELEASE_(partyListPresenter_);
  RELEASE_(uiInterface_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, 0, -1, 1, -1 },
    { NULL, "V", 0x1, -1, -1, 0, -1, 2, -1 },
    { NULL, "V", 0x1, -1, -1, 0, -1, 3, -1 },
    { NULL, "V", 0x1, -1, -1, 0, -1, 4, -1 },
    { NULL, "V", 0x1, -1, -1, 0, -1, 5, -1 },
    { NULL, "V", 0x1, -1, -1, 0, -1, 6, -1 },
    { NULL, "V", 0x1, -1, -1, 0, -1, 7, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(setUp);
  methods[2].selector = @selector(callRefreshPartyList);
  methods[3].selector = @selector(callParty);
  methods[4].selector = @selector(createParty);
  methods[5].selector = @selector(deleteParty);
  methods[6].selector = @selector(countPeople);
  methods[7].selector = @selector(allPeople);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "dataProvider_", "LPDDataProvider;", .constantValue.asLong = 0, 0x0, -1, -1, -1, 8 },
    { "partyListPresenter_", "LPPPartyListPresenter;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "uiInterface_", "LPPPartyListPresenter_UiInterface;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LJavaLangException;", (void *)&PPPartyListPresenterTest__Annotations$0, (void *)&PPPartyListPresenterTest__Annotations$1, (void *)&PPPartyListPresenterTest__Annotations$2, (void *)&PPPartyListPresenterTest__Annotations$3, (void *)&PPPartyListPresenterTest__Annotations$4, (void *)&PPPartyListPresenterTest__Annotations$5, (void *)&PPPartyListPresenterTest__Annotations$6, (void *)&PPPartyListPresenterTest__Annotations$7 };
  static const J2ObjcClassInfo _PPPartyListPresenterTest = { "PartyListPresenterTest", "com.kgalligan.partyclicker.presenter", ptrTable, methods, fields, 7, 0x1, 8, 3, -1, -1, -1, -1, -1 };
  return &_PPPartyListPresenterTest;
}

@end

void PPPartyListPresenterTest_init(PPPartyListPresenterTest *self) {
  NSObject_init(self);
}

PPPartyListPresenterTest *new_PPPartyListPresenterTest_init() {
  J2OBJC_NEW_IMPL(PPPartyListPresenterTest, init)
}

PPPartyListPresenterTest *create_PPPartyListPresenterTest_init() {
  J2OBJC_CREATE_IMPL(PPPartyListPresenterTest, init)
}

IOSObjectArray *PPPartyListPresenterTest__Annotations$0() {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_OrgJunitBefore() } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

IOSObjectArray *PPPartyListPresenterTest__Annotations$1() {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_OrgJunitTest(OrgJunitTest_None_class_(), 0) } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

IOSObjectArray *PPPartyListPresenterTest__Annotations$2() {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_OrgJunitTest(OrgJunitTest_None_class_(), 0) } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

IOSObjectArray *PPPartyListPresenterTest__Annotations$3() {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_OrgJunitTest(OrgJunitTest_None_class_(), 0) } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

IOSObjectArray *PPPartyListPresenterTest__Annotations$4() {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_OrgJunitTest(OrgJunitTest_None_class_(), 0) } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

IOSObjectArray *PPPartyListPresenterTest__Annotations$5() {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_OrgJunitTest(OrgJunitTest_None_class_(), 0) } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

IOSObjectArray *PPPartyListPresenterTest__Annotations$6() {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_OrgJunitTest(OrgJunitTest_None_class_(), 0) } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

IOSObjectArray *PPPartyListPresenterTest__Annotations$7() {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_JavaxInjectInject() } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(PPPartyListPresenterTest)
