//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_PTDaggerTestNoContextComponent")
#ifdef RESTRICT_PTDaggerTestNoContextComponent
#define INCLUDE_ALL_PTDaggerTestNoContextComponent 0
#else
#define INCLUDE_ALL_PTDaggerTestNoContextComponent 1
#endif
#undef RESTRICT_PTDaggerTestNoContextComponent

#if !defined (PTDaggerTestNoContextComponent_) && (INCLUDE_ALL_PTDaggerTestNoContextComponent || defined(INCLUDE_PTDaggerTestNoContextComponent))
#define PTDaggerTestNoContextComponent_

#define RESTRICT_PTTestNoContextComponent 1
#define INCLUDE_PTTestNoContextComponent 1
#include "PTTestNoContextComponent.h"

@class PDModPersonTaskTest;
@class PPPartyListPresenter;
@class PPPartyListPresenterTest;
@class PPPartyPresenter;
@class PPPartyPresenterTest;
@class PTDaggerTestNoContextComponent_Builder;

@interface PTDaggerTestNoContextComponent : NSObject < PTTestNoContextComponent >

#pragma mark Public

+ (PTDaggerTestNoContextComponent_Builder *)builder;

+ (id<PTTestNoContextComponent>)create;

- (void)injectWithPDModPersonTaskTest:(PDModPersonTaskTest *)taskTest;

- (void)injectWithPPPartyListPresenter:(PPPartyListPresenter *)partyListPresenter;

- (void)injectWithPPPartyListPresenterTest:(PPPartyListPresenterTest *)test;

- (void)injectWithPPPartyPresenter:(PPPartyPresenter *)presenter;

- (void)injectWithPPPartyPresenterTest:(PPPartyPresenterTest *)presenter;

@end

J2OBJC_EMPTY_STATIC_INIT(PTDaggerTestNoContextComponent)

FOUNDATION_EXPORT PTDaggerTestNoContextComponent_Builder *PTDaggerTestNoContextComponent_builder();

FOUNDATION_EXPORT id<PTTestNoContextComponent> PTDaggerTestNoContextComponent_create();

J2OBJC_TYPE_LITERAL_HEADER(PTDaggerTestNoContextComponent)

@compatibility_alias ComKgalliganPartyclickerTestDaggerTestNoContextComponent PTDaggerTestNoContextComponent;

#endif

#if !defined (PTDaggerTestNoContextComponent_Builder_) && (INCLUDE_ALL_PTDaggerTestNoContextComponent || defined(INCLUDE_PTDaggerTestNoContextComponent_Builder))
#define PTDaggerTestNoContextComponent_Builder_

@class PTTestNoContextModule;
@protocol PTTestNoContextComponent;

@interface PTDaggerTestNoContextComponent_Builder : NSObject

#pragma mark Public

- (id<PTTestNoContextComponent>)build;

- (PTDaggerTestNoContextComponent_Builder *)testNoContextModuleWithPTTestNoContextModule:(PTTestNoContextModule *)testNoContextModule;

@end

J2OBJC_EMPTY_STATIC_INIT(PTDaggerTestNoContextComponent_Builder)

J2OBJC_TYPE_LITERAL_HEADER(PTDaggerTestNoContextComponent_Builder)

#endif

#pragma pop_macro("INCLUDE_ALL_PTDaggerTestNoContextComponent")
