//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_PTIOSTestHelper")
#ifdef RESTRICT_PTIOSTestHelper
#define INCLUDE_ALL_PTIOSTestHelper 0
#else
#define INCLUDE_ALL_PTIOSTestHelper 1
#endif
#undef RESTRICT_PTIOSTestHelper

#if !defined (PTIOSTestHelper_) && (INCLUDE_ALL_PTIOSTestHelper || defined(INCLUDE_PTIOSTestHelper))
#define PTIOSTestHelper_

@interface PTIOSTestHelper : NSObject

#pragma mark Public

- (instancetype)init;

+ (jint)runTests;

@end

J2OBJC_EMPTY_STATIC_INIT(PTIOSTestHelper)

FOUNDATION_EXPORT void PTIOSTestHelper_init(PTIOSTestHelper *self);

FOUNDATION_EXPORT PTIOSTestHelper *new_PTIOSTestHelper_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT PTIOSTestHelper *create_PTIOSTestHelper_init();

FOUNDATION_EXPORT jint PTIOSTestHelper_runTests();

J2OBJC_TYPE_LITERAL_HEADER(PTIOSTestHelper)

@compatibility_alias ComKgalliganPartyclickerTestIOSTestHelper PTIOSTestHelper;

#endif

#pragma pop_macro("INCLUDE_ALL_PTIOSTestHelper")
