//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_PTTestAppModule_ProvidesApplicationFactory")
#ifdef RESTRICT_PTTestAppModule_ProvidesApplicationFactory
#define INCLUDE_ALL_PTTestAppModule_ProvidesApplicationFactory 0
#else
#define INCLUDE_ALL_PTTestAppModule_ProvidesApplicationFactory 1
#endif
#undef RESTRICT_PTTestAppModule_ProvidesApplicationFactory

#if !defined (PTTestAppModule_ProvidesApplicationFactory_) && (INCLUDE_ALL_PTTestAppModule_ProvidesApplicationFactory || defined(INCLUDE_PTTestAppModule_ProvidesApplicationFactory))
#define PTTestAppModule_ProvidesApplicationFactory_

#define RESTRICT_DaggerInternalFactory 1
#define INCLUDE_DaggerInternalFactory 1
#include "DaggerInternalFactory.h"

@class AndroidAppApplication;
@class PTTestAppModule;

@interface PTTestAppModule_ProvidesApplicationFactory : NSObject < DaggerInternalFactory >

#pragma mark Public

- (instancetype)initWithPTTestAppModule:(PTTestAppModule *)module;

+ (id<DaggerInternalFactory>)createWithPTTestAppModule:(PTTestAppModule *)module;

- (AndroidAppApplication *)get;

@end

J2OBJC_EMPTY_STATIC_INIT(PTTestAppModule_ProvidesApplicationFactory)

FOUNDATION_EXPORT void PTTestAppModule_ProvidesApplicationFactory_initWithPTTestAppModule_(PTTestAppModule_ProvidesApplicationFactory *self, PTTestAppModule *module);

FOUNDATION_EXPORT PTTestAppModule_ProvidesApplicationFactory *new_PTTestAppModule_ProvidesApplicationFactory_initWithPTTestAppModule_(PTTestAppModule *module) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT PTTestAppModule_ProvidesApplicationFactory *create_PTTestAppModule_ProvidesApplicationFactory_initWithPTTestAppModule_(PTTestAppModule *module);

FOUNDATION_EXPORT id<DaggerInternalFactory> PTTestAppModule_ProvidesApplicationFactory_createWithPTTestAppModule_(PTTestAppModule *module);

J2OBJC_TYPE_LITERAL_HEADER(PTTestAppModule_ProvidesApplicationFactory)

@compatibility_alias ComKgalliganPartyclickerTestTestAppModule_ProvidesApplicationFactory PTTestAppModule_ProvidesApplicationFactory;

#endif

#pragma pop_macro("INCLUDE_ALL_PTTestAppModule_ProvidesApplicationFactory")
