//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_CoTouchlabDopplTestingVisualJunitRunner")
#ifdef RESTRICT_CoTouchlabDopplTestingVisualJunitRunner
#define INCLUDE_ALL_CoTouchlabDopplTestingVisualJunitRunner 0
#else
#define INCLUDE_ALL_CoTouchlabDopplTestingVisualJunitRunner 1
#endif
#undef RESTRICT_CoTouchlabDopplTestingVisualJunitRunner

#if !defined (CoTouchlabDopplTestingVisualJunitRunner_) && (INCLUDE_ALL_CoTouchlabDopplTestingVisualJunitRunner || defined(INCLUDE_CoTouchlabDopplTestingVisualJunitRunner))
#define CoTouchlabDopplTestingVisualJunitRunner_

@class IOSObjectArray;

@interface CoTouchlabDopplTestingVisualJunitRunner : NSObject

#pragma mark Public

- (instancetype)init;

- (void)goRun;

#pragma mark Protected

- (IOSObjectArray *)testClasses;

@end

J2OBJC_EMPTY_STATIC_INIT(CoTouchlabDopplTestingVisualJunitRunner)

FOUNDATION_EXPORT void CoTouchlabDopplTestingVisualJunitRunner_init(CoTouchlabDopplTestingVisualJunitRunner *self);

J2OBJC_TYPE_LITERAL_HEADER(CoTouchlabDopplTestingVisualJunitRunner)

#endif

#pragma pop_macro("INCLUDE_ALL_CoTouchlabDopplTestingVisualJunitRunner")
