//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "AndroidAppApplication.h"
#include "J2ObjC_source.h"
#include "PAppManager.h"
#include "PPDaggerComponent.h"

@interface PAppManager () {
 @public
  AndroidAppApplication *application_;
  id<PPDaggerComponent> daggerComponent_;
}

- (instancetype)initWithAndroidAppApplication:(AndroidAppApplication *)application
                        withPPDaggerComponent:(id<PPDaggerComponent>)daggerComponent;

@end

J2OBJC_FIELD_SETTER(PAppManager, application_, AndroidAppApplication *)
J2OBJC_FIELD_SETTER(PAppManager, daggerComponent_, id<PPDaggerComponent>)

inline PAppManager *PAppManager_get_instance();
inline PAppManager *PAppManager_set_instance(PAppManager *value);
static PAppManager *PAppManager_instance;
J2OBJC_STATIC_FIELD_OBJ(PAppManager, instance, PAppManager *)

__attribute__((unused)) static void PAppManager_initWithAndroidAppApplication_withPPDaggerComponent_(PAppManager *self, AndroidAppApplication *application, id<PPDaggerComponent> daggerComponent);

__attribute__((unused)) static PAppManager *new_PAppManager_initWithAndroidAppApplication_withPPDaggerComponent_(AndroidAppApplication *application, id<PPDaggerComponent> daggerComponent) NS_RETURNS_RETAINED;

__attribute__((unused)) static PAppManager *create_PAppManager_initWithAndroidAppApplication_withPPDaggerComponent_(AndroidAppApplication *application, id<PPDaggerComponent> daggerComponent);

@implementation PAppManager

- (instancetype)initWithAndroidAppApplication:(AndroidAppApplication *)application
                        withPPDaggerComponent:(id<PPDaggerComponent>)daggerComponent {
  PAppManager_initWithAndroidAppApplication_withPPDaggerComponent_(self, application, daggerComponent);
  return self;
}

+ (void)init__WithAndroidAppApplication:(AndroidAppApplication *)application
                  withPPDaggerComponent:(id<PPDaggerComponent>)presenterComponent {
  PAppManager_init__WithAndroidAppApplication_withPPDaggerComponent_(application, presenterComponent);
}

- (AndroidAppApplication *)getApplication {
  return application_;
}

- (id<PPDaggerComponent>)getDaggerComponent {
  return daggerComponent_;
}

+ (PAppManager *)getInstance {
  return PAppManager_getInstance();
}

- (void)dealloc {
  RELEASE_(application_);
  RELEASE_(daggerComponent_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x2, -1, 0, -1, -1, -1, -1 },
    { NULL, "V", 0x9, 1, 0, -1, -1, -1, -1 },
    { NULL, "LAndroidAppApplication;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LPPDaggerComponent;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LPAppManager;", 0x9, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithAndroidAppApplication:withPPDaggerComponent:);
  methods[1].selector = @selector(init__WithAndroidAppApplication:withPPDaggerComponent:);
  methods[2].selector = @selector(getApplication);
  methods[3].selector = @selector(getDaggerComponent);
  methods[4].selector = @selector(getInstance);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "application_", "LAndroidAppApplication;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "daggerComponent_", "LPPDaggerComponent;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "instance", "LPAppManager;", .constantValue.asLong = 0, 0xa, -1, 2, -1, -1 },
  };
  static const void *ptrTable[] = { "LAndroidAppApplication;LPPDaggerComponent;", "init", &PAppManager_instance };
  static const J2ObjcClassInfo _PAppManager = { "AppManager", "com.kgalligan.partyclicker", ptrTable, methods, fields, 7, 0x1, 5, 3, -1, -1, -1, -1, -1 };
  return &_PAppManager;
}

@end

void PAppManager_initWithAndroidAppApplication_withPPDaggerComponent_(PAppManager *self, AndroidAppApplication *application, id<PPDaggerComponent> daggerComponent) {
  NSObject_init(self);
  JreStrongAssign(&self->application_, application);
  JreStrongAssign(&self->daggerComponent_, daggerComponent);
}

PAppManager *new_PAppManager_initWithAndroidAppApplication_withPPDaggerComponent_(AndroidAppApplication *application, id<PPDaggerComponent> daggerComponent) {
  J2OBJC_NEW_IMPL(PAppManager, initWithAndroidAppApplication_withPPDaggerComponent_, application, daggerComponent)
}

PAppManager *create_PAppManager_initWithAndroidAppApplication_withPPDaggerComponent_(AndroidAppApplication *application, id<PPDaggerComponent> daggerComponent) {
  J2OBJC_CREATE_IMPL(PAppManager, initWithAndroidAppApplication_withPPDaggerComponent_, application, daggerComponent)
}

void PAppManager_init__WithAndroidAppApplication_withPPDaggerComponent_(AndroidAppApplication *application, id<PPDaggerComponent> presenterComponent) {
  PAppManager_initialize();
  JreStrongAssignAndConsume(&PAppManager_instance, new_PAppManager_initWithAndroidAppApplication_withPPDaggerComponent_(application, presenterComponent));
}

PAppManager *PAppManager_getInstance() {
  PAppManager_initialize();
  return PAppManager_instance;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(PAppManager)
