//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_PDDateTypeConverter")
#ifdef RESTRICT_PDDateTypeConverter
#define INCLUDE_ALL_PDDateTypeConverter 0
#else
#define INCLUDE_ALL_PDDateTypeConverter 1
#endif
#undef RESTRICT_PDDateTypeConverter

#if !defined (PDDateTypeConverter_) && (INCLUDE_ALL_PDDateTypeConverter || defined(INCLUDE_PDDateTypeConverter))
#define PDDateTypeConverter_

@class JavaLangLong;
@class JavaUtilDate;

@interface PDDateTypeConverter : NSObject

#pragma mark Public

- (instancetype)init;

- (JavaLangLong *)dateToTimestampWithJavaUtilDate:(JavaUtilDate *)date;

- (JavaUtilDate *)fromTimestampWithJavaLangLong:(JavaLangLong *)value;

@end

J2OBJC_EMPTY_STATIC_INIT(PDDateTypeConverter)

FOUNDATION_EXPORT void PDDateTypeConverter_init(PDDateTypeConverter *self);

FOUNDATION_EXPORT PDDateTypeConverter *new_PDDateTypeConverter_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT PDDateTypeConverter *create_PDDateTypeConverter_init();

J2OBJC_TYPE_LITERAL_HEADER(PDDateTypeConverter)

@compatibility_alias ComKgalliganPartyclickerDataDateTypeConverter PDDateTypeConverter;

#endif

#pragma pop_macro("INCLUDE_ALL_PDDateTypeConverter")
