//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "AndroidContentContext.h"
#include "AndroidDatabaseDatabaseUtils.h"
#include "AndroidDatabaseSqliteSQLiteDatabase.h"
#include "CoTouchlabSqueakyDaoDao.h"
#include "CoTouchlabSqueakyDbSqliteSQLiteDatabaseImpl.h"
#include "CoTouchlabSqueakyDbSqliteSqueakyOpenHelper.h"
#include "CoTouchlabSqueakyStmtWhere.h"
#include "CoTouchlabSqueakyTableTableUtils.h"
#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "PDDatabaseHelper.h"
#include "PDParty.h"
#include "PDPerson.h"
#include "java/lang/Exception.h"
#include "java/lang/Integer.h"
#include "java/lang/RuntimeException.h"
#include "java/lang/Void.h"
#include "java/sql/SQLException.h"
#include "java/util/Date.h"
#include "java/util/List.h"
#include "java/util/concurrent/Callable.h"

#pragma clang diagnostic ignored "-Wprotocol"

@interface PDDatabaseHelper () {
 @public
  IOSObjectArray *tableClasses_;
}

@end

J2OBJC_FIELD_SETTER(PDDatabaseHelper, tableClasses_, IOSObjectArray *)

inline NSString *PDDatabaseHelper_get_DATABASE_FILE_NAME();
static NSString *PDDatabaseHelper_DATABASE_FILE_NAME = @"db";
J2OBJC_STATIC_FIELD_OBJ_FINAL(PDDatabaseHelper, DATABASE_FILE_NAME, NSString *)

inline jint PDDatabaseHelper_get_BASELINE();
#define PDDatabaseHelper_BASELINE 5
J2OBJC_STATIC_FIELD_CONSTANT(PDDatabaseHelper, BASELINE, jint)

inline jint PDDatabaseHelper_get_CURRENT_VERSION();
#define PDDatabaseHelper_CURRENT_VERSION 5
J2OBJC_STATIC_FIELD_CONSTANT(PDDatabaseHelper, CURRENT_VERSION, jint)

@interface PDDatabaseHelper_$Lambda$1 : NSObject < JavaUtilConcurrentCallable > {
 @public
  PDDatabaseHelper *this$0_;
  PDParty *val$party_;
}

- (id)call;

@end

J2OBJC_EMPTY_STATIC_INIT(PDDatabaseHelper_$Lambda$1)

__attribute__((unused)) static void PDDatabaseHelper_$Lambda$1_initWithPDDatabaseHelper_withPDParty_(PDDatabaseHelper_$Lambda$1 *self, PDDatabaseHelper *outer$, PDParty *capture$0);

__attribute__((unused)) static PDDatabaseHelper_$Lambda$1 *new_PDDatabaseHelper_$Lambda$1_initWithPDDatabaseHelper_withPDParty_(PDDatabaseHelper *outer$, PDParty *capture$0) NS_RETURNS_RETAINED;

__attribute__((unused)) static PDDatabaseHelper_$Lambda$1 *create_PDDatabaseHelper_$Lambda$1_initWithPDDatabaseHelper_withPDParty_(PDDatabaseHelper *outer$, PDParty *capture$0);

@implementation PDDatabaseHelper

- (instancetype)initWithAndroidContentContext:(AndroidContentContext *)context {
  PDDatabaseHelper_initWithAndroidContentContext_(self, context);
  return self;
}

- (void)onCreateWithAndroidDatabaseSqliteSQLiteDatabase:(AndroidDatabaseSqliteSQLiteDatabase *)db {
  @try {
    CoTouchlabSqueakyTableTableUtils_createTablesWithCoTouchlabSqueakyDbSQLiteDatabase_withIOSClassArray_(create_CoTouchlabSqueakyDbSqliteSQLiteDatabaseImpl_initWithAndroidDatabaseSqliteSQLiteDatabase_(db), tableClasses_);
  }
  @catch (JavaSqlSQLException *e) {
    @throw create_JavaLangRuntimeException_initWithNSException_(e);
  }
}

- (void)onUpgradeWithAndroidDatabaseSqliteSQLiteDatabase:(AndroidDatabaseSqliteSQLiteDatabase *)db
                                                 withInt:(jint)oldVersion
                                                 withInt:(jint)newVersion {
  @try {
    CoTouchlabSqueakyTableTableUtils_dropTablesWithCoTouchlabSqueakyDbSQLiteDatabase_withBoolean_withIOSClassArray_(create_CoTouchlabSqueakyDbSqliteSQLiteDatabaseImpl_initWithAndroidDatabaseSqliteSQLiteDatabase_(db), true, tableClasses_);
  }
  @catch (JavaSqlSQLException *e) {
    @throw create_JavaLangRuntimeException_initWithNSException_(e);
  }
  [self onCreateWithAndroidDatabaseSqliteSQLiteDatabase:db];
}

- (void)onOpenWithAndroidDatabaseSqliteSQLiteDatabase:(AndroidDatabaseSqliteSQLiteDatabase *)db {
  [super onOpenWithAndroidDatabaseSqliteSQLiteDatabase:db];
  [((AndroidDatabaseSqliteSQLiteDatabase *) nil_chk(db)) execSQLWithNSString:@"PRAGMA foreign_keys=ON;"];
}

- (void)performTransactionOrThrowRuntimeWithJavaUtilConcurrentCallable:(id<JavaUtilConcurrentCallable>)transaction {
  AndroidDatabaseSqliteSQLiteDatabase *db = [self getWritableDatabase];
  @try {
    [((AndroidDatabaseSqliteSQLiteDatabase *) nil_chk(db)) beginTransaction];
    [((id<JavaUtilConcurrentCallable>) nil_chk(transaction)) call];
    [db setTransactionSuccessful];
  }
  @catch (JavaLangException *e) {
    @throw create_JavaLangRuntimeException_initWithNSException_(e);
  }
  @finally {
    [db endTransaction];
  }
}

- (id<CoTouchlabSqueakyDaoDao>)getPartyDao {
  return [self getDaoWithIOSClass:PDParty_class_()];
}

- (id<CoTouchlabSqueakyDaoDao>)getPersonDao {
  return [self getDaoWithIOSClass:PDPerson_class_()];
}

- (jint)countCurrentPartyWithInt:(jint)partyId {
  return (jint) AndroidDatabaseDatabaseUtils_longForQueryWithAndroidDatabaseSqliteSQLiteDatabase_withNSString_withNSStringArray_([self getWritableDatabase], @"select sum(val) from person where party_id = ?", [IOSObjectArray arrayWithObjects:(id[]){ JavaLangInteger_toStringWithInt_(partyId) } count:1 type:NSString_class_()]);
}

- (id<JavaUtilList>)allPeopleForPartyWithPDParty:(PDParty *)party {
  @try {
    CoTouchlabSqueakyStmtWhere *where = create_CoTouchlabSqueakyStmtWhere_initWithCoTouchlabSqueakyDaoDao_([self getPersonDao]);
    [where eqWithNSString:@"party" withId:party];
    return [((id<CoTouchlabSqueakyDaoDao_QueryModifiers>) nil_chk([((id<CoTouchlabSqueakyDaoDao_QueryModifiers>) nil_chk([((id<CoTouchlabSqueakyDaoDao>) nil_chk([self getPersonDao])) queryWithCoTouchlabSqueakyDaoQuery:where])) orderByWithNSString:@"recorded"])) list];
  }
  @catch (JavaSqlSQLException *e) {
    @throw create_JavaLangRuntimeException_initWithNSException_(e);
  }
}

- (void)addPersonWithPDParty:(PDParty *)party
                 withBoolean:(jboolean)coming {
  @try {
    PDPerson *person = create_PDPerson_init();
    JreStrongAssign(&person->party_, party);
    JreStrongAssignAndConsume(&person->recorded_, new_JavaUtilDate_init());
    person->val_ = (jshort) (coming ? 1 : -1);
    [((id<CoTouchlabSqueakyDaoDao>) nil_chk([self getPersonDao])) createWithId:person];
  }
  @catch (JavaSqlSQLException *e) {
    @throw create_JavaLangRuntimeException_initWithNSException_(e);
  }
}

- (id<JavaUtilList>)allParties {
  @try {
    return [((id<CoTouchlabSqueakyDaoDao_QueryModifiers>) nil_chk([((id<CoTouchlabSqueakyDaoDao_QueryModifiers>) nil_chk([((id<CoTouchlabSqueakyDaoDao>) nil_chk([self getPartyDao])) queryForAll])) orderByWithNSString:@"created desc"])) list];
  }
  @catch (JavaSqlSQLException *e) {
    @throw create_JavaLangRuntimeException_initWithNSException_(e);
  }
}

- (PDParty *)createPartyWithNSString:(NSString *)name {
  @try {
    PDParty *party = create_PDParty_init();
    JreStrongAssignAndConsume(&party->created_, new_JavaUtilDate_init());
    JreStrongAssign(&party->name_, name);
    [((id<CoTouchlabSqueakyDaoDao>) nil_chk([self getPartyDao])) createWithId:party];
    return party;
  }
  @catch (JavaSqlSQLException *e) {
    @throw create_JavaLangRuntimeException_initWithNSException_(e);
  }
}

- (void)deletePartyWithPDParty:(PDParty *)party {
  [self performTransactionOrThrowRuntimeWithJavaUtilConcurrentCallable:create_PDDatabaseHelper_$Lambda$1_initWithPDDatabaseHelper_withPDParty_(self, party)];
}

- (PDParty *)loadPartyWithInt:(jint)id_ {
  @try {
    return [((id<CoTouchlabSqueakyDaoDao>) nil_chk([self getPartyDao])) queryForIdWithId:JavaLangInteger_valueOfWithInt_(id_)];
  }
  @catch (JavaSqlSQLException *e) {
    @throw create_JavaLangRuntimeException_initWithNSException_(e);
  }
}

- (void)dealloc {
  RELEASE_(tableClasses_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 1, 2, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 3, 4, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 5, 2, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 6, 7, -1, 8, -1, -1 },
    { NULL, "LCoTouchlabSqueakyDaoDao;", 0x1, -1, -1, -1, 9, -1, -1 },
    { NULL, "LCoTouchlabSqueakyDaoDao;", 0x1, -1, -1, -1, 10, -1, -1 },
    { NULL, "I", 0x1, 11, 12, -1, -1, -1, -1 },
    { NULL, "LJavaUtilList;", 0x1, 13, 14, -1, 15, -1, -1 },
    { NULL, "V", 0x1, 16, 17, -1, -1, -1, -1 },
    { NULL, "LJavaUtilList;", 0x1, -1, -1, -1, 18, -1, -1 },
    { NULL, "LPDParty;", 0x1, 19, 20, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 21, 14, -1, -1, -1, -1 },
    { NULL, "LPDParty;", 0x1, 22, 12, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithAndroidContentContext:);
  methods[1].selector = @selector(onCreateWithAndroidDatabaseSqliteSQLiteDatabase:);
  methods[2].selector = @selector(onUpgradeWithAndroidDatabaseSqliteSQLiteDatabase:withInt:withInt:);
  methods[3].selector = @selector(onOpenWithAndroidDatabaseSqliteSQLiteDatabase:);
  methods[4].selector = @selector(performTransactionOrThrowRuntimeWithJavaUtilConcurrentCallable:);
  methods[5].selector = @selector(getPartyDao);
  methods[6].selector = @selector(getPersonDao);
  methods[7].selector = @selector(countCurrentPartyWithInt:);
  methods[8].selector = @selector(allPeopleForPartyWithPDParty:);
  methods[9].selector = @selector(addPersonWithPDParty:withBoolean:);
  methods[10].selector = @selector(allParties);
  methods[11].selector = @selector(createPartyWithNSString:);
  methods[12].selector = @selector(deletePartyWithPDParty:);
  methods[13].selector = @selector(loadPartyWithInt:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "DATABASE_FILE_NAME", "LNSString;", .constantValue.asLong = 0, 0x1a, -1, 23, -1, -1 },
    { "BASELINE", "I", .constantValue.asInt = PDDatabaseHelper_BASELINE, 0x1a, -1, -1, -1, -1 },
    { "CURRENT_VERSION", "I", .constantValue.asInt = PDDatabaseHelper_CURRENT_VERSION, 0x1a, -1, -1, -1, -1 },
    { "tableClasses_", "[LIOSClass;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LAndroidContentContext;", "onCreate", "LAndroidDatabaseSqliteSQLiteDatabase;", "onUpgrade", "LAndroidDatabaseSqliteSQLiteDatabase;II", "onOpen", "performTransactionOrThrowRuntime", "LJavaUtilConcurrentCallable;", "(Ljava/util/concurrent/Callable<Ljava/lang/Void;>;)V", "()Lco/touchlab/squeaky/dao/Dao<Lcom/kgalligan/partyclicker/data/Party;>;", "()Lco/touchlab/squeaky/dao/Dao<Lcom/kgalligan/partyclicker/data/Person;>;", "countCurrentParty", "I", "allPeopleForParty", "LPDParty;", "(Lcom/kgalligan/partyclicker/data/Party;)Ljava/util/List<Lcom/kgalligan/partyclicker/data/Person;>;", "addPerson", "LPDParty;Z", "()Ljava/util/List<Lcom/kgalligan/partyclicker/data/Party;>;", "createParty", "LNSString;", "deleteParty", "loadParty", &PDDatabaseHelper_DATABASE_FILE_NAME };
  static const J2ObjcClassInfo _PDDatabaseHelper = { "DatabaseHelper", "com.kgalligan.partyclicker.data", ptrTable, methods, fields, 7, 0x1, 14, 4, -1, -1, -1, -1, -1 };
  return &_PDDatabaseHelper;
}

@end

void PDDatabaseHelper_initWithAndroidContentContext_(PDDatabaseHelper *self, AndroidContentContext *context) {
  CoTouchlabSqueakyDbSqliteSqueakyOpenHelper_initWithAndroidContentContext_withNSString_withAndroidDatabaseSqliteSQLiteDatabase_CursorFactory_withInt_(self, context, PDDatabaseHelper_DATABASE_FILE_NAME, nil, PDDatabaseHelper_CURRENT_VERSION);
  JreStrongAssignAndConsume(&self->tableClasses_, [IOSObjectArray newArrayWithObjects:(id[]){ PDParty_class_(), PDPerson_class_() } count:2 type:IOSClass_class_()]);
}

PDDatabaseHelper *new_PDDatabaseHelper_initWithAndroidContentContext_(AndroidContentContext *context) {
  J2OBJC_NEW_IMPL(PDDatabaseHelper, initWithAndroidContentContext_, context)
}

PDDatabaseHelper *create_PDDatabaseHelper_initWithAndroidContentContext_(AndroidContentContext *context) {
  J2OBJC_CREATE_IMPL(PDDatabaseHelper, initWithAndroidContentContext_, context)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(PDDatabaseHelper)

@implementation PDDatabaseHelper_$Lambda$1

- (id)call {
  CoTouchlabSqueakyStmtWhere *where = create_CoTouchlabSqueakyStmtWhere_initWithCoTouchlabSqueakyDaoDao_([this$0_ getPersonDao]);
  [where eqWithNSString:@"party" withId:val$party_];
  [((id<CoTouchlabSqueakyDaoDao>) nil_chk([this$0_ getPersonDao])) delete__WithCoTouchlabSqueakyDaoQuery:where];
  [((id<CoTouchlabSqueakyDaoDao>) nil_chk([this$0_ getPartyDao])) delete__WithId:val$party_];
  return nil;
}

- (void)dealloc {
  RELEASE_(this$0_);
  RELEASE_(val$party_);
  [super dealloc];
}

@end

void PDDatabaseHelper_$Lambda$1_initWithPDDatabaseHelper_withPDParty_(PDDatabaseHelper_$Lambda$1 *self, PDDatabaseHelper *outer$, PDParty *capture$0) {
  JreStrongAssign(&self->this$0_, outer$);
  JreStrongAssign(&self->val$party_, capture$0);
  NSObject_init(self);
}

PDDatabaseHelper_$Lambda$1 *new_PDDatabaseHelper_$Lambda$1_initWithPDDatabaseHelper_withPDParty_(PDDatabaseHelper *outer$, PDParty *capture$0) {
  J2OBJC_NEW_IMPL(PDDatabaseHelper_$Lambda$1, initWithPDDatabaseHelper_withPDParty_, outer$, capture$0)
}

PDDatabaseHelper_$Lambda$1 *create_PDDatabaseHelper_$Lambda$1_initWithPDDatabaseHelper_withPDParty_(PDDatabaseHelper *outer$, PDParty *capture$0) {
  J2OBJC_CREATE_IMPL(PDDatabaseHelper_$Lambda$1, initWithPDDatabaseHelper_withPDParty_, outer$, capture$0)
}
