//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_PDPartyDatabase")
#ifdef RESTRICT_PDPartyDatabase
#define INCLUDE_ALL_PDPartyDatabase 0
#else
#define INCLUDE_ALL_PDPartyDatabase 1
#endif
#undef RESTRICT_PDPartyDatabase

#if !defined (PDPartyDatabase_) && (INCLUDE_ALL_PDPartyDatabase || defined(INCLUDE_PDPartyDatabase))
#define PDPartyDatabase_

#define RESTRICT_AndroidArchPersistenceRoomRoomDatabase 1
#define INCLUDE_AndroidArchPersistenceRoomRoomDatabase 1
#include "AndroidArchPersistenceRoomRoomDatabase.h"

@protocol PDPartyDao;

@interface PDPartyDatabase : AndroidArchPersistenceRoomRoomDatabase

#pragma mark Public

- (instancetype)init;

- (id<PDPartyDao>)partyDao;

@end

J2OBJC_EMPTY_STATIC_INIT(PDPartyDatabase)

FOUNDATION_EXPORT void PDPartyDatabase_init(PDPartyDatabase *self);

J2OBJC_TYPE_LITERAL_HEADER(PDPartyDatabase)

@compatibility_alias ComKgalliganPartyclickerDataPartyDatabase PDPartyDatabase;

#endif

#pragma pop_macro("INCLUDE_ALL_PDPartyDatabase")
