//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "AndroidArchPersistenceDbSupportSQLiteDatabase.h"
#include "AndroidArchPersistenceDbSupportSQLiteOpenHelper.h"
#include "AndroidArchPersistenceRoomDatabaseConfiguration.h"
#include "AndroidArchPersistenceRoomInvalidationTracker.h"
#include "AndroidArchPersistenceRoomRoomOpenHelper.h"
#include "AndroidArchPersistenceRoomUtilTableInfo.h"
#include "AndroidContentContext.h"
#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "PDPartyDao.h"
#include "PDPartyDao_Impl.h"
#include "PDPartyDatabase.h"
#include "PDPartyDatabase_Impl.h"
#include "java/lang/IllegalStateException.h"
#include "java/util/Arrays.h"
#include "java/util/HashMap.h"
#include "java/util/HashSet.h"
#include "java/util/List.h"

@interface PDPartyDatabase_Impl () {
 @public
  volatile_id _partyDao_;
}

@end

J2OBJC_VOLATILE_FIELD_SETTER(PDPartyDatabase_Impl, _partyDao_, id<PDPartyDao>)

@interface PDPartyDatabase_Impl_1 : AndroidArchPersistenceRoomRoomOpenHelper_Delegate {
 @public
  PDPartyDatabase_Impl *this$0_;
}

- (instancetype)initWithPDPartyDatabase_Impl:(PDPartyDatabase_Impl *)outer$;

- (void)createAllTablesWithAndroidArchPersistenceDbSupportSQLiteDatabase:(id<AndroidArchPersistenceDbSupportSQLiteDatabase>)_db;

- (void)dropAllTablesWithAndroidArchPersistenceDbSupportSQLiteDatabase:(id<AndroidArchPersistenceDbSupportSQLiteDatabase>)_db;

- (void)onOpenWithAndroidArchPersistenceDbSupportSQLiteDatabase:(id<AndroidArchPersistenceDbSupportSQLiteDatabase>)_db;

- (void)validateMigrationWithAndroidArchPersistenceDbSupportSQLiteDatabase:(id<AndroidArchPersistenceDbSupportSQLiteDatabase>)_db;

@end

J2OBJC_EMPTY_STATIC_INIT(PDPartyDatabase_Impl_1)

__attribute__((unused)) static void PDPartyDatabase_Impl_1_initWithPDPartyDatabase_Impl_(PDPartyDatabase_Impl_1 *self, PDPartyDatabase_Impl *outer$);

__attribute__((unused)) static PDPartyDatabase_Impl_1 *new_PDPartyDatabase_Impl_1_initWithPDPartyDatabase_Impl_(PDPartyDatabase_Impl *outer$) NS_RETURNS_RETAINED;

__attribute__((unused)) static PDPartyDatabase_Impl_1 *create_PDPartyDatabase_Impl_1_initWithPDPartyDatabase_Impl_(PDPartyDatabase_Impl *outer$);

@implementation PDPartyDatabase_Impl

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  PDPartyDatabase_Impl_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (id<AndroidArchPersistenceDbSupportSQLiteOpenHelper>)createOpenHelperWithAndroidArchPersistenceRoomDatabaseConfiguration:(AndroidArchPersistenceRoomDatabaseConfiguration *)configuration {
  AndroidArchPersistenceDbSupportSQLiteOpenHelper_Callback *_openCallback = create_AndroidArchPersistenceRoomRoomOpenHelper_initWithAndroidArchPersistenceRoomDatabaseConfiguration_withAndroidArchPersistenceRoomRoomOpenHelper_Delegate_withNSString_(configuration, create_PDPartyDatabase_Impl_1_initWithPDPartyDatabase_Impl_(self), @"50f0fe98bcfad6f194acc71c3110c8a9");
  AndroidArchPersistenceDbSupportSQLiteOpenHelper_Configuration *_sqliteConfig = [((AndroidArchPersistenceDbSupportSQLiteOpenHelper_Configuration_Builder *) nil_chk([((AndroidArchPersistenceDbSupportSQLiteOpenHelper_Configuration_Builder *) nil_chk([((AndroidArchPersistenceDbSupportSQLiteOpenHelper_Configuration_Builder *) nil_chk([((AndroidArchPersistenceDbSupportSQLiteOpenHelper_Configuration_Builder *) nil_chk(AndroidArchPersistenceDbSupportSQLiteOpenHelper_Configuration_builderWithAndroidContentContext_(((AndroidArchPersistenceRoomDatabaseConfiguration *) nil_chk(configuration))->context_))) nameWithNSString:configuration->name_])) version__WithInt:1])) callbackWithAndroidArchPersistenceDbSupportSQLiteOpenHelper_Callback:_openCallback])) build];
  id<AndroidArchPersistenceDbSupportSQLiteOpenHelper> _helper = [((id<AndroidArchPersistenceDbSupportSQLiteOpenHelper_Factory>) nil_chk(configuration->sqliteOpenHelperFactory_)) createWithAndroidArchPersistenceDbSupportSQLiteOpenHelper_Configuration:_sqliteConfig];
  return _helper;
}

- (AndroidArchPersistenceRoomInvalidationTracker *)createInvalidationTracker {
  return create_AndroidArchPersistenceRoomInvalidationTracker_initWithAndroidArchPersistenceRoomRoomDatabase_withNSStringArray_(self, [IOSObjectArray arrayWithObjects:(id[]){ @"Party", @"Person" } count:2 type:NSString_class_()]);
}

- (id<PDPartyDao>)partyDao {
  if (JreLoadVolatileId(&_partyDao_) != nil) {
    return JreLoadVolatileId(&_partyDao_);
  }
  else {
    @synchronized(self) {
      if (JreLoadVolatileId(&_partyDao_) == nil) {
        JreVolatileStrongAssign(&_partyDao_, create_PDPartyDao_Impl_initWithAndroidArchPersistenceRoomRoomDatabase_(self));
      }
      return JreLoadVolatileId(&_partyDao_);
    }
  }
}

- (void)__javaClone:(PDPartyDatabase_Impl *)original {
  [super __javaClone:original];
  JreCloneVolatileStrong(&_partyDao_, &original->_partyDao_);
}

- (void)dealloc {
  JreReleaseVolatile(&_partyDao_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LAndroidArchPersistenceDbSupportSQLiteOpenHelper;", 0x4, 0, 1, -1, -1, -1, -1 },
    { NULL, "LAndroidArchPersistenceRoomInvalidationTracker;", 0x4, -1, -1, -1, -1, -1, -1 },
    { NULL, "LPDPartyDao;", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(createOpenHelperWithAndroidArchPersistenceRoomDatabaseConfiguration:);
  methods[2].selector = @selector(createInvalidationTracker);
  methods[3].selector = @selector(partyDao);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "_partyDao_", "LPDPartyDao;", .constantValue.asLong = 0, 0x42, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "createOpenHelper", "LAndroidArchPersistenceRoomDatabaseConfiguration;" };
  static const J2ObjcClassInfo _PDPartyDatabase_Impl = { "PartyDatabase_Impl", "com.kgalligan.partyclicker.data", ptrTable, methods, fields, 7, 0x1, 4, 1, -1, -1, -1, -1, -1 };
  return &_PDPartyDatabase_Impl;
}

@end

void PDPartyDatabase_Impl_init(PDPartyDatabase_Impl *self) {
  PDPartyDatabase_init(self);
}

PDPartyDatabase_Impl *new_PDPartyDatabase_Impl_init() {
  J2OBJC_NEW_IMPL(PDPartyDatabase_Impl, init)
}

PDPartyDatabase_Impl *create_PDPartyDatabase_Impl_init() {
  J2OBJC_CREATE_IMPL(PDPartyDatabase_Impl, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(PDPartyDatabase_Impl)

@implementation PDPartyDatabase_Impl_1

- (instancetype)initWithPDPartyDatabase_Impl:(PDPartyDatabase_Impl *)outer$ {
  PDPartyDatabase_Impl_1_initWithPDPartyDatabase_Impl_(self, outer$);
  return self;
}

- (void)createAllTablesWithAndroidArchPersistenceDbSupportSQLiteDatabase:(id<AndroidArchPersistenceDbSupportSQLiteDatabase>)_db {
  [((id<AndroidArchPersistenceDbSupportSQLiteDatabase>) nil_chk(_db)) execSQLWithNSString:@"CREATE TABLE IF NOT EXISTS `Party` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `name` TEXT, `created` INTEGER)"];
  [_db execSQLWithNSString:@"CREATE TABLE IF NOT EXISTS `Person` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `recorded` INTEGER, `val` INTEGER, `party_id` INTEGER, FOREIGN KEY(`party_id`) REFERENCES `Party`(`id`) ON UPDATE NO ACTION ON DELETE NO ACTION )"];
  [_db execSQLWithNSString:@"CREATE TABLE IF NOT EXISTS room_master_table (id INTEGER PRIMARY KEY,identity_hash TEXT)"];
  [_db execSQLWithNSString:@"INSERT OR REPLACE INTO room_master_table (id,identity_hash) VALUES(42, \"50f0fe98bcfad6f194acc71c3110c8a9\")"];
}

- (void)dropAllTablesWithAndroidArchPersistenceDbSupportSQLiteDatabase:(id<AndroidArchPersistenceDbSupportSQLiteDatabase>)_db {
  [((id<AndroidArchPersistenceDbSupportSQLiteDatabase>) nil_chk(_db)) execSQLWithNSString:@"DROP TABLE IF EXISTS `Party`"];
  [_db execSQLWithNSString:@"DROP TABLE IF EXISTS `Person`"];
}

- (void)onOpenWithAndroidArchPersistenceDbSupportSQLiteDatabase:(id<AndroidArchPersistenceDbSupportSQLiteDatabase>)_db {
  JreVolatileStrongAssign(&this$0_->mDatabase_, _db);
  [((id<AndroidArchPersistenceDbSupportSQLiteDatabase>) nil_chk(_db)) execSQLWithNSString:@"PRAGMA foreign_keys = ON"];
  [this$0_ internalInitInvalidationTrackerWithAndroidArchPersistenceDbSupportSQLiteDatabase:_db];
}

- (void)validateMigrationWithAndroidArchPersistenceDbSupportSQLiteDatabase:(id<AndroidArchPersistenceDbSupportSQLiteDatabase>)_db {
  JavaUtilHashMap *_columnsParty = create_JavaUtilHashMap_initWithInt_(3);
  [_columnsParty putWithId:@"id" withId:create_AndroidArchPersistenceRoomUtilTableInfo_Column_initWithNSString_withNSString_withInt_(@"id", @"INTEGER", 1)];
  [_columnsParty putWithId:@"name" withId:create_AndroidArchPersistenceRoomUtilTableInfo_Column_initWithNSString_withNSString_withInt_(@"name", @"TEXT", 0)];
  [_columnsParty putWithId:@"created" withId:create_AndroidArchPersistenceRoomUtilTableInfo_Column_initWithNSString_withNSString_withInt_(@"created", @"INTEGER", 0)];
  JavaUtilHashSet *_foreignKeysParty = create_JavaUtilHashSet_initWithInt_(0);
  AndroidArchPersistenceRoomUtilTableInfo *_infoParty = create_AndroidArchPersistenceRoomUtilTableInfo_initWithNSString_withJavaUtilMap_withJavaUtilSet_(@"Party", _columnsParty, _foreignKeysParty);
  AndroidArchPersistenceRoomUtilTableInfo *_existingParty = AndroidArchPersistenceRoomUtilTableInfo_readWithAndroidArchPersistenceDbSupportSQLiteDatabase_withNSString_(_db, @"Party");
  if (![_infoParty isEqual:_existingParty]) {
    @throw create_JavaLangIllegalStateException_initWithNSString_(JreStrcat("$@$@", @"Migration didn't properly handle Party(com.kgalligan.partyclicker.data.Party).\n Expected:\n", _infoParty, @"\n Found:\n", _existingParty));
  }
  JavaUtilHashMap *_columnsPerson = create_JavaUtilHashMap_initWithInt_(4);
  [_columnsPerson putWithId:@"id" withId:create_AndroidArchPersistenceRoomUtilTableInfo_Column_initWithNSString_withNSString_withInt_(@"id", @"INTEGER", 1)];
  [_columnsPerson putWithId:@"recorded" withId:create_AndroidArchPersistenceRoomUtilTableInfo_Column_initWithNSString_withNSString_withInt_(@"recorded", @"INTEGER", 0)];
  [_columnsPerson putWithId:@"val" withId:create_AndroidArchPersistenceRoomUtilTableInfo_Column_initWithNSString_withNSString_withInt_(@"val", @"INTEGER", 0)];
  [_columnsPerson putWithId:@"party_id" withId:create_AndroidArchPersistenceRoomUtilTableInfo_Column_initWithNSString_withNSString_withInt_(@"party_id", @"INTEGER", 0)];
  JavaUtilHashSet *_foreignKeysPerson = create_JavaUtilHashSet_initWithInt_(1);
  [_foreignKeysPerson addWithId:create_AndroidArchPersistenceRoomUtilTableInfo_ForeignKey_initWithNSString_withNSString_withNSString_withJavaUtilList_withJavaUtilList_(@"Party", @"NO ACTION", @"NO ACTION", JavaUtilArrays_asListWithNSObjectArray_([IOSObjectArray arrayWithObjects:(id[]){ @"party_id" } count:1 type:NSString_class_()]), JavaUtilArrays_asListWithNSObjectArray_([IOSObjectArray arrayWithObjects:(id[]){ @"id" } count:1 type:NSString_class_()]))];
  AndroidArchPersistenceRoomUtilTableInfo *_infoPerson = create_AndroidArchPersistenceRoomUtilTableInfo_initWithNSString_withJavaUtilMap_withJavaUtilSet_(@"Person", _columnsPerson, _foreignKeysPerson);
  AndroidArchPersistenceRoomUtilTableInfo *_existingPerson = AndroidArchPersistenceRoomUtilTableInfo_readWithAndroidArchPersistenceDbSupportSQLiteDatabase_withNSString_(_db, @"Person");
  if (![_infoPerson isEqual:_existingPerson]) {
    @throw create_JavaLangIllegalStateException_initWithNSString_(JreStrcat("$@$@", @"Migration didn't properly handle Person(com.kgalligan.partyclicker.data.Person).\n Expected:\n", _infoPerson, @"\n Found:\n", _existingPerson));
  }
}

- (void)dealloc {
  RELEASE_(this$0_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 0, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 2, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 3, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x4, 4, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithPDPartyDatabase_Impl:);
  methods[1].selector = @selector(createAllTablesWithAndroidArchPersistenceDbSupportSQLiteDatabase:);
  methods[2].selector = @selector(dropAllTablesWithAndroidArchPersistenceDbSupportSQLiteDatabase:);
  methods[3].selector = @selector(onOpenWithAndroidArchPersistenceDbSupportSQLiteDatabase:);
  methods[4].selector = @selector(validateMigrationWithAndroidArchPersistenceDbSupportSQLiteDatabase:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", "LPDPartyDatabase_Impl;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "createAllTables", "LAndroidArchPersistenceDbSupportSQLiteDatabase;", "dropAllTables", "onOpen", "validateMigration", "LPDPartyDatabase_Impl;", "createOpenHelperWithAndroidArchPersistenceRoomDatabaseConfiguration:" };
  static const J2ObjcClassInfo _PDPartyDatabase_Impl_1 = { "", "com.kgalligan.partyclicker.data", ptrTable, methods, fields, 7, 0x8018, 5, 1, 5, -1, 6, -1, -1 };
  return &_PDPartyDatabase_Impl_1;
}

@end

void PDPartyDatabase_Impl_1_initWithPDPartyDatabase_Impl_(PDPartyDatabase_Impl_1 *self, PDPartyDatabase_Impl *outer$) {
  JreStrongAssign(&self->this$0_, outer$);
  AndroidArchPersistenceRoomRoomOpenHelper_Delegate_init(self);
}

PDPartyDatabase_Impl_1 *new_PDPartyDatabase_Impl_1_initWithPDPartyDatabase_Impl_(PDPartyDatabase_Impl *outer$) {
  J2OBJC_NEW_IMPL(PDPartyDatabase_Impl_1, initWithPDPartyDatabase_Impl_, outer$)
}

PDPartyDatabase_Impl_1 *create_PDPartyDatabase_Impl_1_initWithPDPartyDatabase_Impl_(PDPartyDatabase_Impl *outer$) {
  J2OBJC_CREATE_IMPL(PDPartyDatabase_Impl_1, initWithPDPartyDatabase_Impl_, outer$)
}
