//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_PPAppModule_ProvidesCrashReporterFactory")
#ifdef RESTRICT_PPAppModule_ProvidesCrashReporterFactory
#define INCLUDE_ALL_PPAppModule_ProvidesCrashReporterFactory 0
#else
#define INCLUDE_ALL_PPAppModule_ProvidesCrashReporterFactory 1
#endif
#undef RESTRICT_PPAppModule_ProvidesCrashReporterFactory

#if !defined (PPAppModule_ProvidesCrashReporterFactory_) && (INCLUDE_ALL_PPAppModule_ProvidesCrashReporterFactory || defined(INCLUDE_PPAppModule_ProvidesCrashReporterFactory))
#define PPAppModule_ProvidesCrashReporterFactory_

#define RESTRICT_DaggerInternalFactory 1
#define INCLUDE_DaggerInternalFactory 1
#include "DaggerInternalFactory.h"

@class PPAppModule;
@protocol PPCrashReporter;

@interface PPAppModule_ProvidesCrashReporterFactory : NSObject < DaggerInternalFactory >

#pragma mark Public

- (instancetype)initWithPPAppModule:(PPAppModule *)module;

+ (id<DaggerInternalFactory>)createWithPPAppModule:(PPAppModule *)module;

- (id<PPCrashReporter>)get;

@end

J2OBJC_EMPTY_STATIC_INIT(PPAppModule_ProvidesCrashReporterFactory)

FOUNDATION_EXPORT void PPAppModule_ProvidesCrashReporterFactory_initWithPPAppModule_(PPAppModule_ProvidesCrashReporterFactory *self, PPAppModule *module);

FOUNDATION_EXPORT PPAppModule_ProvidesCrashReporterFactory *new_PPAppModule_ProvidesCrashReporterFactory_initWithPPAppModule_(PPAppModule *module) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT PPAppModule_ProvidesCrashReporterFactory *create_PPAppModule_ProvidesCrashReporterFactory_initWithPPAppModule_(PPAppModule *module);

FOUNDATION_EXPORT id<DaggerInternalFactory> PPAppModule_ProvidesCrashReporterFactory_createWithPPAppModule_(PPAppModule *module);

J2OBJC_TYPE_LITERAL_HEADER(PPAppModule_ProvidesCrashReporterFactory)

@compatibility_alias ComKgalliganPartyclickerPresenterAppModule_ProvidesCrashReporterFactory PPAppModule_ProvidesCrashReporterFactory;

#endif

#pragma pop_macro("INCLUDE_ALL_PPAppModule_ProvidesCrashReporterFactory")
