//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "DaggerComponent.h"
#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "PPAppModule.h"
#include "PPDaggerComponent.h"
#include "java/lang/annotation/Annotation.h"
#include "javax/inject/Singleton.h"

@interface PPDaggerComponent : NSObject

@end

__attribute__((unused)) static IOSObjectArray *PPDaggerComponent__Annotations$0();

@implementation PPDaggerComponent

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "V", 0x401, 0, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x401, 0, 2, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(injectWithPPPartyListPresenter:);
  methods[1].selector = @selector(injectWithPPPartyPresenter:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "inject", "LPPPartyListPresenter;", "LPPPartyPresenter;", (void *)&PPDaggerComponent__Annotations$0 };
  static const J2ObjcClassInfo _PPDaggerComponent = { "DaggerComponent", "com.kgalligan.partyclicker.presenter", ptrTable, methods, NULL, 7, 0x609, 2, 0, -1, -1, -1, -1, 3 };
  return &_PPDaggerComponent;
}

@end

IOSObjectArray *PPDaggerComponent__Annotations$0() {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_JavaxInjectSingleton(), create_DaggerComponent([IOSObjectArray arrayWithLength:0 type:IOSClass_class_()], [IOSObjectArray arrayWithObjects:(id[]){ PPAppModule_class_() } count:1 type:IOSClass_class_()]) } count:2 type:JavaLangAnnotationAnnotation_class_()];
}

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(PPDaggerComponent)
