//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "PPLogCrashReporter.h"
#include "android/util/Log.h"

J2OBJC_INITIALIZED_DEFN(PPLogCrashReporter)

NSString *PPLogCrashReporter_TAG;

@implementation PPLogCrashReporter

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  PPLogCrashReporter_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (void)logWithNSString:(NSString *)s {
  AndroidUtilLog_wWithNSString_withNSString_(PPLogCrashReporter_TAG, s);
}

- (void)reportWithNSException:(NSException *)t {
  AndroidUtilLog_eWithNSString_withNSString_withNSException_(PPLogCrashReporter_TAG, nil, t);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 0, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 2, 3, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(logWithNSString:);
  methods[2].selector = @selector(reportWithNSException:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "TAG", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 4, -1, -1 },
  };
  static const void *ptrTable[] = { "log", "LNSString;", "report", "LNSException;", &PPLogCrashReporter_TAG };
  static const J2ObjcClassInfo _PPLogCrashReporter = { "LogCrashReporter", "com.kgalligan.partyclicker.presenter", ptrTable, methods, fields, 7, 0x1, 3, 1, -1, -1, -1, -1, -1 };
  return &_PPLogCrashReporter;
}

+ (void)initialize {
  if (self == [PPLogCrashReporter class]) {
    JreStrongAssign(&PPLogCrashReporter_TAG, [PPLogCrashReporter_class_() getSimpleName]);
    J2OBJC_SET_INITIALIZED(PPLogCrashReporter)
  }
}

@end

void PPLogCrashReporter_init(PPLogCrashReporter *self) {
  NSObject_init(self);
}

PPLogCrashReporter *new_PPLogCrashReporter_init() {
  J2OBJC_NEW_IMPL(PPLogCrashReporter, init)
}

PPLogCrashReporter *create_PPLogCrashReporter_init() {
  J2OBJC_CREATE_IMPL(PPLogCrashReporter, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(PPLogCrashReporter)
