//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidArchCoreExecutorAppToolkitTaskExecutor")
#ifdef RESTRICT_AndroidArchCoreExecutorAppToolkitTaskExecutor
#define INCLUDE_ALL_AndroidArchCoreExecutorAppToolkitTaskExecutor 0
#else
#define INCLUDE_ALL_AndroidArchCoreExecutorAppToolkitTaskExecutor 1
#endif
#undef RESTRICT_AndroidArchCoreExecutorAppToolkitTaskExecutor

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (AndroidArchCoreExecutorAppToolkitTaskExecutor_) && (INCLUDE_ALL_AndroidArchCoreExecutorAppToolkitTaskExecutor || defined(INCLUDE_AndroidArchCoreExecutorAppToolkitTaskExecutor))
#define AndroidArchCoreExecutorAppToolkitTaskExecutor_

#define RESTRICT_AndroidArchCoreExecutorTaskExecutor 1
#define INCLUDE_AndroidArchCoreExecutorTaskExecutor 1
#include "AndroidArchCoreExecutorTaskExecutor.h"

@protocol JavaLangRunnable;

@interface AndroidArchCoreExecutorAppToolkitTaskExecutor : AndroidArchCoreExecutorTaskExecutor

#pragma mark Public

- (void)executeOnDiskIOWithJavaLangRunnable:(id<JavaLangRunnable>)runnable;

+ (AndroidArchCoreExecutorAppToolkitTaskExecutor *)getInstance;

- (jboolean)isMainThread;

- (void)postToMainThreadWithJavaLangRunnable:(id<JavaLangRunnable>)runnable;

- (void)setDelegateWithAndroidArchCoreExecutorTaskExecutor:(AndroidArchCoreExecutorTaskExecutor *)taskExecutor;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidArchCoreExecutorAppToolkitTaskExecutor)

FOUNDATION_EXPORT AndroidArchCoreExecutorAppToolkitTaskExecutor *AndroidArchCoreExecutorAppToolkitTaskExecutor_getInstance();

J2OBJC_TYPE_LITERAL_HEADER(AndroidArchCoreExecutorAppToolkitTaskExecutor)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AndroidArchCoreExecutorAppToolkitTaskExecutor")
