//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidArchPersistenceDbSupportSQLiteDatabase")
#ifdef RESTRICT_AndroidArchPersistenceDbSupportSQLiteDatabase
#define INCLUDE_ALL_AndroidArchPersistenceDbSupportSQLiteDatabase 0
#else
#define INCLUDE_ALL_AndroidArchPersistenceDbSupportSQLiteDatabase 1
#endif
#undef RESTRICT_AndroidArchPersistenceDbSupportSQLiteDatabase

#if !defined (AndroidArchPersistenceDbSupportSQLiteDatabase_) && (INCLUDE_ALL_AndroidArchPersistenceDbSupportSQLiteDatabase || defined(INCLUDE_AndroidArchPersistenceDbSupportSQLiteDatabase))
#define AndroidArchPersistenceDbSupportSQLiteDatabase_

#define RESTRICT_JavaIoCloseable 1
#define INCLUDE_JavaIoCloseable 1
#include "java/io/Closeable.h"

@class AndroidContentContentValues;
@class IOSObjectArray;
@class JavaUtilLocale;
@protocol AndroidArchPersistenceDbSupportSQLiteQuery;
@protocol AndroidArchPersistenceDbSupportSQLiteStatement;
@protocol AndroidDatabaseCursor;
@protocol AndroidDatabaseSqliteSQLiteDatabase_CursorFactory;
@protocol AndroidDatabaseSqliteSQLiteTransactionListener;
@protocol JavaUtilList;

@protocol AndroidArchPersistenceDbSupportSQLiteDatabase < JavaIoCloseable, JavaObject >

- (id<AndroidArchPersistenceDbSupportSQLiteStatement>)compileStatementWithNSString:(NSString *)sql;

- (void)beginTransaction;

- (void)beginTransactionNonExclusive;

- (void)beginTransactionWithListenerWithAndroidDatabaseSqliteSQLiteTransactionListener:(id<AndroidDatabaseSqliteSQLiteTransactionListener>)transactionListener;

- (void)beginTransactionWithListenerNonExclusiveWithAndroidDatabaseSqliteSQLiteTransactionListener:(id<AndroidDatabaseSqliteSQLiteTransactionListener>)transactionListener;

- (void)endTransaction;

- (void)setTransactionSuccessful;

- (jboolean)inTransaction;

- (jboolean)isDbLockedByCurrentThread;

- (jboolean)yieldIfContendedSafely;

- (jboolean)yieldIfContendedSafelyWithLong:(jlong)sleepAfterYieldDelay;

- (jint)getVersion;

- (void)setVersionWithInt:(jint)version_;

- (jlong)getMaximumSize;

- (jlong)setMaximumSizeWithLong:(jlong)numBytes;

- (jlong)getPageSize;

- (void)setPageSizeWithLong:(jlong)numBytes;

- (id<AndroidDatabaseCursor>)queryWithBoolean:(jboolean)distinct
                                 withNSString:(NSString *)table
                            withNSStringArray:(IOSObjectArray *)columns
                                 withNSString:(NSString *)selection
                            withNSStringArray:(IOSObjectArray *)selectionArgs
                                 withNSString:(NSString *)groupBy
                                 withNSString:(NSString *)having
                                 withNSString:(NSString *)orderBy
                                 withNSString:(NSString *)limit;

- (id<AndroidDatabaseCursor>)queryWithFactoryWithAndroidDatabaseSqliteSQLiteDatabase_CursorFactory:(id<AndroidDatabaseSqliteSQLiteDatabase_CursorFactory>)cursorFactory
                                                                                       withBoolean:(jboolean)distinct
                                                                                      withNSString:(NSString *)table
                                                                                 withNSStringArray:(IOSObjectArray *)columns
                                                                                      withNSString:(NSString *)selection
                                                                                 withNSStringArray:(IOSObjectArray *)selectionArgs
                                                                                      withNSString:(NSString *)groupBy
                                                                                      withNSString:(NSString *)having
                                                                                      withNSString:(NSString *)orderBy
                                                                                      withNSString:(NSString *)limit;

- (id<AndroidDatabaseCursor>)queryWithNSString:(NSString *)table
                             withNSStringArray:(IOSObjectArray *)columns
                                  withNSString:(NSString *)selection
                             withNSStringArray:(IOSObjectArray *)selectionArgs
                                  withNSString:(NSString *)groupBy
                                  withNSString:(NSString *)having
                                  withNSString:(NSString *)orderBy;

- (id<AndroidDatabaseCursor>)queryWithNSString:(NSString *)table
                             withNSStringArray:(IOSObjectArray *)columns
                                  withNSString:(NSString *)selection
                             withNSStringArray:(IOSObjectArray *)selectionArgs
                                  withNSString:(NSString *)groupBy
                                  withNSString:(NSString *)having
                                  withNSString:(NSString *)orderBy
                                  withNSString:(NSString *)limit;

- (id<AndroidDatabaseCursor>)rawQueryWithNSString:(NSString *)sql
                                withNSStringArray:(IOSObjectArray *)selectionArgs;

- (id<AndroidDatabaseCursor>)rawQueryWithFactoryWithAndroidDatabaseSqliteSQLiteDatabase_CursorFactory:(id<AndroidDatabaseSqliteSQLiteDatabase_CursorFactory>)cursorFactory
                                                                                         withNSString:(NSString *)sql
                                                                                    withNSStringArray:(IOSObjectArray *)selectionArgs
                                                                                         withNSString:(NSString *)editTable;

- (id<AndroidDatabaseCursor>)rawQueryWithAndroidArchPersistenceDbSupportSQLiteQuery:(id<AndroidArchPersistenceDbSupportSQLiteQuery>)query;

- (jlong)insertWithNSString:(NSString *)table
               withNSString:(NSString *)nullColumnHack
withAndroidContentContentValues:(AndroidContentContentValues *)values;

- (jlong)insertOrThrowWithNSString:(NSString *)table
                      withNSString:(NSString *)nullColumnHack
   withAndroidContentContentValues:(AndroidContentContentValues *)values;

- (jlong)replaceWithNSString:(NSString *)table
                withNSString:(NSString *)nullColumnHack
withAndroidContentContentValues:(AndroidContentContentValues *)initialValues;

- (jlong)replaceOrThrowWithNSString:(NSString *)table
                       withNSString:(NSString *)nullColumnHack
    withAndroidContentContentValues:(AndroidContentContentValues *)initialValues;

- (jlong)insertWithOnConflictWithNSString:(NSString *)table
                             withNSString:(NSString *)nullColumnHack
          withAndroidContentContentValues:(AndroidContentContentValues *)initialValues
                                  withInt:(jint)conflictAlgorithm;

- (jint)delete__WithNSString:(NSString *)table
                withNSString:(NSString *)whereClause
           withNSStringArray:(IOSObjectArray *)whereArgs;

- (jint)updateWithNSString:(NSString *)table
withAndroidContentContentValues:(AndroidContentContentValues *)values
              withNSString:(NSString *)whereClause
         withNSStringArray:(IOSObjectArray *)whereArgs;

- (jint)updateWithOnConflictWithNSString:(NSString *)table
         withAndroidContentContentValues:(AndroidContentContentValues *)values
                            withNSString:(NSString *)whereClause
                       withNSStringArray:(IOSObjectArray *)whereArgs
                                 withInt:(jint)conflictAlgorithm;

- (void)execSQLWithNSString:(NSString *)sql;

- (void)execSQLWithNSString:(NSString *)sql
          withNSObjectArray:(IOSObjectArray *)bindArgs;

- (jboolean)isReadOnly;

- (jboolean)isOpen;

- (jboolean)needUpgradeWithInt:(jint)newVersion;

- (NSString *)getPath;

- (void)setLocaleWithJavaUtilLocale:(JavaUtilLocale *)locale;

- (void)setMaxSqlCacheSizeWithInt:(jint)cacheSize;

- (void)setForeignKeyConstraintsEnabledWithBoolean:(jboolean)enable;

- (jboolean)enableWriteAheadLogging;

- (void)disableWriteAheadLogging;

- (jboolean)isWriteAheadLoggingEnabled;

- (id<JavaUtilList>)getAttachedDbs;

- (jboolean)isDatabaseIntegrityOk;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidArchPersistenceDbSupportSQLiteDatabase)

J2OBJC_TYPE_LITERAL_HEADER(AndroidArchPersistenceDbSupportSQLiteDatabase)

#endif

#pragma pop_macro("INCLUDE_ALL_AndroidArchPersistenceDbSupportSQLiteDatabase")
