//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidArchPersistenceRoomRoomDatabase")
#ifdef RESTRICT_AndroidArchPersistenceRoomRoomDatabase
#define INCLUDE_ALL_AndroidArchPersistenceRoomRoomDatabase 0
#else
#define INCLUDE_ALL_AndroidArchPersistenceRoomRoomDatabase 1
#endif
#undef RESTRICT_AndroidArchPersistenceRoomRoomDatabase

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (AndroidArchPersistenceRoomRoomDatabase_) && (INCLUDE_ALL_AndroidArchPersistenceRoomRoomDatabase || defined(INCLUDE_AndroidArchPersistenceRoomRoomDatabase))
#define AndroidArchPersistenceRoomRoomDatabase_

@class AndroidArchPersistenceRoomDatabaseConfiguration;
@class AndroidArchPersistenceRoomInvalidationTracker;
@class IOSObjectArray;
@protocol AndroidArchPersistenceDbSupportSQLiteDatabase;
@protocol AndroidArchPersistenceDbSupportSQLiteOpenHelper;
@protocol AndroidArchPersistenceDbSupportSQLiteQuery;
@protocol AndroidArchPersistenceDbSupportSQLiteStatement;
@protocol AndroidDatabaseCursor;

@interface AndroidArchPersistenceRoomRoomDatabase : NSObject {
 @public
  volatile_id mDatabase_;
}

#pragma mark Public

- (instancetype)init;

- (void)assertNotMainThread;

- (void)beginTransaction;

- (void)close;

- (id<AndroidArchPersistenceDbSupportSQLiteStatement>)compileStatementWithNSString:(NSString *)sql;

- (void)endTransaction;

- (AndroidArchPersistenceRoomInvalidationTracker *)getInvalidationTracker;

- (id<AndroidArchPersistenceDbSupportSQLiteOpenHelper>)getOpenHelper;

- (void)init__WithAndroidArchPersistenceRoomDatabaseConfiguration:(AndroidArchPersistenceRoomDatabaseConfiguration *)configuration OBJC_METHOD_FAMILY_NONE;

- (jboolean)inTransaction;

- (jboolean)isOpen;

- (id<AndroidDatabaseCursor>)queryWithNSString:(NSString *)sql
                             withNSStringArray:(IOSObjectArray *)selectionArgs;

- (id<AndroidDatabaseCursor>)queryWithAndroidArchPersistenceDbSupportSQLiteQuery:(id<AndroidArchPersistenceDbSupportSQLiteQuery>)query;

- (void)setTransactionSuccessful;

#pragma mark Protected

- (AndroidArchPersistenceRoomInvalidationTracker *)createInvalidationTracker;

- (id<AndroidArchPersistenceDbSupportSQLiteOpenHelper>)createOpenHelperWithAndroidArchPersistenceRoomDatabaseConfiguration:(AndroidArchPersistenceRoomDatabaseConfiguration *)config;

- (void)internalInitInvalidationTrackerWithAndroidArchPersistenceDbSupportSQLiteDatabase:(id<AndroidArchPersistenceDbSupportSQLiteDatabase>)db;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidArchPersistenceRoomRoomDatabase)

J2OBJC_VOLATILE_FIELD_SETTER(AndroidArchPersistenceRoomRoomDatabase, mDatabase_, id<AndroidArchPersistenceDbSupportSQLiteDatabase>)

FOUNDATION_EXPORT void AndroidArchPersistenceRoomRoomDatabase_init(AndroidArchPersistenceRoomRoomDatabase *self);

J2OBJC_TYPE_LITERAL_HEADER(AndroidArchPersistenceRoomRoomDatabase)

#endif

#if !defined (AndroidArchPersistenceRoomRoomDatabase_Builder_) && (INCLUDE_ALL_AndroidArchPersistenceRoomRoomDatabase || defined(INCLUDE_AndroidArchPersistenceRoomRoomDatabase_Builder))
#define AndroidArchPersistenceRoomRoomDatabase_Builder_

@class AndroidArchPersistenceRoomRoomDatabase;
@class AndroidContentContext;
@class IOSClass;
@class IOSObjectArray;
@protocol AndroidArchPersistenceDbSupportSQLiteOpenHelper_Factory;

@interface AndroidArchPersistenceRoomRoomDatabase_Builder : NSObject

#pragma mark Public

- (AndroidArchPersistenceRoomRoomDatabase_Builder *)addMigrationsWithAndroidArchPersistenceRoomMigrationMigrationArray:(IOSObjectArray *)migrations;

- (AndroidArchPersistenceRoomRoomDatabase_Builder *)allowMainThreadQueries;

- (AndroidArchPersistenceRoomRoomDatabase *)build;

- (AndroidArchPersistenceRoomRoomDatabase_Builder *)openHelperFactoryWithAndroidArchPersistenceDbSupportSQLiteOpenHelper_Factory:(id<AndroidArchPersistenceDbSupportSQLiteOpenHelper_Factory>)factory;

#pragma mark Package-Private

- (instancetype)initWithAndroidContentContext:(AndroidContentContext *)context
                                 withIOSClass:(IOSClass *)klass
                                 withNSString:(NSString *)name;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidArchPersistenceRoomRoomDatabase_Builder)

FOUNDATION_EXPORT void AndroidArchPersistenceRoomRoomDatabase_Builder_initWithAndroidContentContext_withIOSClass_withNSString_(AndroidArchPersistenceRoomRoomDatabase_Builder *self, AndroidContentContext *context, IOSClass *klass, NSString *name);

FOUNDATION_EXPORT AndroidArchPersistenceRoomRoomDatabase_Builder *new_AndroidArchPersistenceRoomRoomDatabase_Builder_initWithAndroidContentContext_withIOSClass_withNSString_(AndroidContentContext *context, IOSClass *klass, NSString *name) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AndroidArchPersistenceRoomRoomDatabase_Builder *create_AndroidArchPersistenceRoomRoomDatabase_Builder_initWithAndroidContentContext_withIOSClass_withNSString_(AndroidContentContext *context, IOSClass *klass, NSString *name);

J2OBJC_TYPE_LITERAL_HEADER(AndroidArchPersistenceRoomRoomDatabase_Builder)

#endif

#if !defined (AndroidArchPersistenceRoomRoomDatabase_MigrationContainer_) && (INCLUDE_ALL_AndroidArchPersistenceRoomRoomDatabase || defined(INCLUDE_AndroidArchPersistenceRoomRoomDatabase_MigrationContainer))
#define AndroidArchPersistenceRoomRoomDatabase_MigrationContainer_

@class IOSObjectArray;
@protocol JavaUtilList;

@interface AndroidArchPersistenceRoomRoomDatabase_MigrationContainer : NSObject

#pragma mark Public

- (instancetype)init;

- (void)addMigrationsWithAndroidArchPersistenceRoomMigrationMigrationArray:(IOSObjectArray *)migrations;

- (id<JavaUtilList>)findMigrationPathWithInt:(jint)start
                                     withInt:(jint)end;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidArchPersistenceRoomRoomDatabase_MigrationContainer)

FOUNDATION_EXPORT void AndroidArchPersistenceRoomRoomDatabase_MigrationContainer_init(AndroidArchPersistenceRoomRoomDatabase_MigrationContainer *self);

FOUNDATION_EXPORT AndroidArchPersistenceRoomRoomDatabase_MigrationContainer *new_AndroidArchPersistenceRoomRoomDatabase_MigrationContainer_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AndroidArchPersistenceRoomRoomDatabase_MigrationContainer *create_AndroidArchPersistenceRoomRoomDatabase_MigrationContainer_init();

J2OBJC_TYPE_LITERAL_HEADER(AndroidArchPersistenceRoomRoomDatabase_MigrationContainer)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AndroidArchPersistenceRoomRoomDatabase")
