//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_PDPartyDatabase_Impl")
#ifdef RESTRICT_PDPartyDatabase_Impl
#define INCLUDE_ALL_PDPartyDatabase_Impl 0
#else
#define INCLUDE_ALL_PDPartyDatabase_Impl 1
#endif
#undef RESTRICT_PDPartyDatabase_Impl

#if !defined (PDPartyDatabase_Impl_) && (INCLUDE_ALL_PDPartyDatabase_Impl || defined(INCLUDE_PDPartyDatabase_Impl))
#define PDPartyDatabase_Impl_

#define RESTRICT_PDPartyDatabase 1
#define INCLUDE_PDPartyDatabase 1
#include "PDPartyDatabase.h"

@class AndroidArchPersistenceRoomDatabaseConfiguration;
@class AndroidArchPersistenceRoomInvalidationTracker;
@protocol AndroidArchPersistenceDbSupportSQLiteOpenHelper;
@protocol PDPartyDao;

@interface PDPartyDatabase_Impl : PDPartyDatabase

#pragma mark Public

- (instancetype)init;

- (id<PDPartyDao>)partyDao;

#pragma mark Protected

- (AndroidArchPersistenceRoomInvalidationTracker *)createInvalidationTracker;

- (id<AndroidArchPersistenceDbSupportSQLiteOpenHelper>)createOpenHelperWithAndroidArchPersistenceRoomDatabaseConfiguration:(AndroidArchPersistenceRoomDatabaseConfiguration *)configuration;

@end

J2OBJC_EMPTY_STATIC_INIT(PDPartyDatabase_Impl)

FOUNDATION_EXPORT void PDPartyDatabase_Impl_init(PDPartyDatabase_Impl *self);

FOUNDATION_EXPORT PDPartyDatabase_Impl *new_PDPartyDatabase_Impl_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT PDPartyDatabase_Impl *create_PDPartyDatabase_Impl_init();

J2OBJC_TYPE_LITERAL_HEADER(PDPartyDatabase_Impl)

@compatibility_alias ComKgalliganPartyclickerDataPartyDatabase_Impl PDPartyDatabase_Impl;

#endif

#pragma pop_macro("INCLUDE_ALL_PDPartyDatabase_Impl")
