//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "AndroidDatabaseCursor.h"
#include "CoTouchlabSqueakyDaoDao.h"
#include "CoTouchlabSqueakyDaoDaoHelper.h"
#include "CoTouchlabSqueakyDaoModelDao.h"
#include "CoTouchlabSqueakyDaoSqueakyContext.h"
#include "CoTouchlabSqueakyDbSQLiteStatement.h"
#include "CoTouchlabSqueakyFieldDataPersister.h"
#include "CoTouchlabSqueakyFieldDataType.h"
#include "CoTouchlabSqueakyFieldFieldType.h"
#include "CoTouchlabSqueakyFieldFieldsEnum.h"
#include "CoTouchlabSqueakyFieldForeignCollectionInfo.h"
#include "CoTouchlabSqueakyFieldOrmLiteHelper.h"
#include "CoTouchlabSqueakyTableTableInfo.h"
#include "CoTouchlabSqueakyTableTransientCache.h"
#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "PDParty$Configuration.h"
#include "PDParty.h"
#include "PDPerson$Configuration.h"
#include "PDPerson.h"
#include "java/lang/Enum.h"
#include "java/lang/IllegalArgumentException.h"
#include "java/lang/Integer.h"
#include "java/util/ArrayList.h"
#include "java/util/Date.h"
#include "java/util/List.h"

@interface PDPerson_Configuration_Fields () {
 @public
  CoTouchlabSqueakyFieldFieldType *fieldType_;
}

@end

J2OBJC_FIELD_SETTER(PDPerson_Configuration_Fields, fieldType_, CoTouchlabSqueakyFieldFieldType *)

__attribute__((unused)) static void PDPerson_Configuration_Fields_initWithCoTouchlabSqueakyFieldFieldType_withNSString_withInt_(PDPerson_Configuration_Fields *self, CoTouchlabSqueakyFieldFieldType *fieldType, NSString *__name, jint __ordinal);

J2OBJC_INITIALIZED_DEFN(PDPerson_Configuration)

PDPerson_Configuration *PDPerson_Configuration_instance;

@implementation PDPerson_Configuration

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  PDPerson_Configuration_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (PDPerson *)createObjectWithAndroidDatabaseCursor:(id<AndroidDatabaseCursor>)results {
  PDPerson *data = create_PDPerson_init();
  return data;
}

- (void)fillRowWithId:(PDPerson *)data
withAndroidDatabaseCursor:(id<AndroidDatabaseCursor>)results
withCoTouchlabSqueakyDaoModelDao:(CoTouchlabSqueakyDaoModelDao *)modelDao
withCoTouchlabSqueakyDaoDao_ForeignRefreshArray:(IOSObjectArray *)foreignRefreshMap
withCoTouchlabSqueakyTableTransientCache:(CoTouchlabSqueakyTableTransientCache *)objectCache {
  if (![((id<AndroidDatabaseCursor>) nil_chk(results)) isNullWithInt:0]) ((PDPerson *) nil_chk(data))->id__ = [results getIntWithInt:0];
  if (![results isNullWithInt:1]) JreStrongAssign(&((PDPerson *) nil_chk(data))->recorded_, (JavaUtilDate *) cast_chk([((id<CoTouchlabSqueakyFieldDataPersister>) nil_chk([((CoTouchlabSqueakyFieldFieldType *) nil_chk([((id<CoTouchlabSqueakyFieldFieldsEnum>) nil_chk(IOSObjectArray_Get(nil_chk(fields_), 1))) getFieldType])) getDataPersister])) resultToJavaWithCoTouchlabSqueakyFieldFieldType:[((id<CoTouchlabSqueakyFieldFieldsEnum>) nil_chk(IOSObjectArray_Get(nil_chk(fields_), 1))) getFieldType] withAndroidDatabaseCursor:results withInt:1], [JavaUtilDate class]));
  if (![results isNullWithInt:2]) ((PDPerson *) nil_chk(data))->val_ = [results getShortWithInt:2];
  if (![results isNullWithInt:3]) {
    PDParty *__party = [((PDParty_Configuration *) nil_chk(JreLoadStatic(PDParty_Configuration, instance))) createObjectWithAndroidDatabaseCursor:nil];
    [JreLoadStatic(PDParty_Configuration, instance) assignIdWithId:__party withId:JavaLangInteger_valueOfWithInt_([results getIntWithInt:3])];
    if (foreignRefreshMap != nil && CoTouchlabSqueakyDaoDaoHelper_findRefreshWithCoTouchlabSqueakyDaoDao_ForeignRefreshArray_withNSString_(foreignRefreshMap, @"party") != nil) {
      [((id<CoTouchlabSqueakyDaoDao>) nil_chk([((CoTouchlabSqueakyDaoSqueakyContext *) nil_chk([((CoTouchlabSqueakyDaoModelDao *) nil_chk(modelDao)) getOpenHelper])) getDaoWithIOSClass:PDParty_class_()])) refreshWithId:__party withCoTouchlabSqueakyDaoDao_ForeignRefreshArray:((CoTouchlabSqueakyDaoDao_ForeignRefresh *) nil_chk(CoTouchlabSqueakyDaoDaoHelper_findRefreshWithCoTouchlabSqueakyDaoDao_ForeignRefreshArray_withNSString_(foreignRefreshMap, @"party")))->refreshFields_];
    }
    JreStrongAssign(&((PDPerson *) nil_chk(data))->party_, __party);
  }
}

- (void)assignIdWithId:(PDPerson *)data
                withId:(id)val {
  ((PDPerson *) nil_chk(data))->id__ = [((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk(CoTouchlabSqueakyFieldOrmLiteHelper_safeConvertWithIOSClass_withId_([IOSClass intClass], val), [JavaLangInteger class]))) intValue];
}

- (JavaLangInteger *)extractIdWithId:(PDPerson *)data {
  if (data == nil) {
    return nil;
  }
  JavaLangInteger *val = JavaLangInteger_valueOfWithInt_(data->id__);
  val = [val intValue] == 0 ? nil : val;
  return val;
}

- (void)bindValsWithCoTouchlabSqueakyDbSQLiteStatement:(id<CoTouchlabSqueakyDbSQLiteStatement>)stmt
                                                withId:(PDPerson *)data {
  id val1 = ((PDPerson *) nil_chk(data))->recorded_;
  if (val1 == nil) {
    [((id<CoTouchlabSqueakyDbSQLiteStatement>) nil_chk(stmt)) bindNullWithInt:1];
  }
  else {
    [((id<CoTouchlabSqueakyDbSQLiteStatement>) nil_chk(stmt)) bindStringWithInt:1 withNSString:[nil_chk([((id<CoTouchlabSqueakyFieldDataPersister>) nil_chk([((CoTouchlabSqueakyFieldFieldType *) nil_chk([((id<CoTouchlabSqueakyFieldFieldsEnum>) nil_chk(IOSObjectArray_Get(nil_chk(fields_), 1))) getFieldType])) getDataPersister])) javaToSqlArgWithCoTouchlabSqueakyFieldFieldType:[((id<CoTouchlabSqueakyFieldFieldsEnum>) nil_chk(IOSObjectArray_Get(nil_chk(fields_), 1))) getFieldType] withId:val1]) description]];
  }
  [stmt bindLongWithInt:2 withLong:data->val_];
  PDParty *val3 = data->party_;
  if (val3 == nil) {
    [stmt bindNullWithInt:3];
  }
  else {
    [stmt bindLongWithInt:3 withLong:[((JavaLangInteger *) nil_chk([((PDParty_Configuration *) nil_chk(JreLoadStatic(PDParty_Configuration, instance))) extractIdWithId:val3])) intValue]];
  }
  [stmt bindLongWithInt:4 withLong:data->id__];
}

- (void)bindCreateValsWithCoTouchlabSqueakyDbSQLiteStatement:(id<CoTouchlabSqueakyDbSQLiteStatement>)stmt
                                                      withId:(PDPerson *)data {
  id val1 = ((PDPerson *) nil_chk(data))->recorded_;
  if (val1 == nil) {
    [((id<CoTouchlabSqueakyDbSQLiteStatement>) nil_chk(stmt)) bindNullWithInt:1];
  }
  else {
    [((id<CoTouchlabSqueakyDbSQLiteStatement>) nil_chk(stmt)) bindStringWithInt:1 withNSString:[nil_chk([((id<CoTouchlabSqueakyFieldDataPersister>) nil_chk([((CoTouchlabSqueakyFieldFieldType *) nil_chk([((id<CoTouchlabSqueakyFieldFieldsEnum>) nil_chk(IOSObjectArray_Get(nil_chk(fields_), 1))) getFieldType])) getDataPersister])) javaToSqlArgWithCoTouchlabSqueakyFieldFieldType:[((id<CoTouchlabSqueakyFieldFieldsEnum>) nil_chk(IOSObjectArray_Get(nil_chk(fields_), 1))) getFieldType] withId:val1]) description]];
  }
  [stmt bindLongWithInt:2 withLong:data->val_];
  PDParty *val3 = data->party_;
  if (val3 == nil) {
    [stmt bindNullWithInt:3];
  }
  else {
    [stmt bindLongWithInt:3 withLong:[((JavaLangInteger *) nil_chk([((PDParty_Configuration *) nil_chk(JreLoadStatic(PDParty_Configuration, instance))) extractIdWithId:val3])) intValue]];
  }
}

- (NSString *)objectToStringWithId:(PDPerson *)data {
  return @"heyo";
}

- (jboolean)objectsEqualWithId:(PDPerson *)d1
                        withId:(PDPerson *)d2 {
  return false;
}

- (void)fillForeignCollectionWithId:(PDPerson *)data
   withCoTouchlabSqueakyDaoModelDao:(CoTouchlabSqueakyDaoModelDao *)modelDao
                       withNSString:(NSString *)fieldName {
}

+ (IOSObjectArray *)getFields {
  return PDPerson_Configuration_getFields();
}

+ (IOSObjectArray *)getForeignConfigs {
  return PDPerson_Configuration_getForeignConfigs();
}

- (CoTouchlabSqueakyTableTableInfo *)getTableConfig {
  CoTouchlabSqueakyTableTableInfo *config = create_CoTouchlabSqueakyTableTableInfo_initWithIOSClass_withNSString_withCoTouchlabSqueakyFieldFieldsEnumArray_withCoTouchlabSqueakyFieldForeignCollectionInfoArray_(PDPerson_class_(), @"person", PDPerson_Configuration_getFields(), PDPerson_Configuration_getForeignConfigs());
  return config;
}

- (void)dealloc {
  RELEASE_(fields_);
  RELEASE_(foreignConfigs_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LPDPerson;", 0x1, 0, 1, 2, -1, -1, -1 },
    { NULL, "V", 0x1, 3, 4, 2, 5, -1, -1 },
    { NULL, "V", 0x1, 6, 7, -1, -1, -1, -1 },
    { NULL, "LJavaLangInteger;", 0x1, 8, 9, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 10, 11, 2, -1, -1, -1 },
    { NULL, "V", 0x1, 12, 11, 2, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, 13, 9, 2, -1, -1, -1 },
    { NULL, "Z", 0x1, 14, 15, 2, -1, -1, -1 },
    { NULL, "V", 0x1, 16, 17, 2, 18, -1, -1 },
    { NULL, "[LCoTouchlabSqueakyFieldFieldsEnum;", 0x9, -1, -1, -1, -1, -1, -1 },
    { NULL, "[LCoTouchlabSqueakyFieldForeignCollectionInfo;", 0x9, -1, -1, -1, -1, -1, -1 },
    { NULL, "LCoTouchlabSqueakyTableTableInfo;", 0x1, -1, -1, 2, 19, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(createObjectWithAndroidDatabaseCursor:);
  methods[2].selector = @selector(fillRowWithId:withAndroidDatabaseCursor:withCoTouchlabSqueakyDaoModelDao:withCoTouchlabSqueakyDaoDao_ForeignRefreshArray:withCoTouchlabSqueakyTableTransientCache:);
  methods[3].selector = @selector(assignIdWithId:withId:);
  methods[4].selector = @selector(extractIdWithId:);
  methods[5].selector = @selector(bindValsWithCoTouchlabSqueakyDbSQLiteStatement:withId:);
  methods[6].selector = @selector(bindCreateValsWithCoTouchlabSqueakyDbSQLiteStatement:withId:);
  methods[7].selector = @selector(objectToStringWithId:);
  methods[8].selector = @selector(objectsEqualWithId:withId:);
  methods[9].selector = @selector(fillForeignCollectionWithId:withCoTouchlabSqueakyDaoModelDao:withNSString:);
  methods[10].selector = @selector(getFields);
  methods[11].selector = @selector(getForeignConfigs);
  methods[12].selector = @selector(getTableConfig);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "instance", "LPDPerson_Configuration;", .constantValue.asLong = 0, 0x19, -1, 20, -1, -1 },
    { "fields_", "[LCoTouchlabSqueakyFieldFieldsEnum;", .constantValue.asLong = 0, 0x0, -1, -1, -1, -1 },
    { "foreignConfigs_", "[LCoTouchlabSqueakyFieldForeignCollectionInfo;", .constantValue.asLong = 0, 0x0, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "createObject", "LAndroidDatabaseCursor;", "LJavaSqlSQLException;", "fillRow", "LPDPerson;LAndroidDatabaseCursor;LCoTouchlabSqueakyDaoModelDao;[LCoTouchlabSqueakyDaoDao_ForeignRefresh;LCoTouchlabSqueakyTableTransientCache;", "(Lcom/kgalligan/partyclicker/data/Person;Landroid/database/Cursor;Lco/touchlab/squeaky/dao/ModelDao<Lcom/kgalligan/partyclicker/data/Person;>;[Lco/touchlab/squeaky/dao/Dao$ForeignRefresh;Lco/touchlab/squeaky/table/TransientCache;)V", "assignId", "LPDPerson;LNSObject;", "extractId", "LPDPerson;", "bindVals", "LCoTouchlabSqueakyDbSQLiteStatement;LPDPerson;", "bindCreateVals", "objectToString", "objectsEqual", "LPDPerson;LPDPerson;", "fillForeignCollection", "LPDPerson;LCoTouchlabSqueakyDaoModelDao;LNSString;", "(Lcom/kgalligan/partyclicker/data/Person;Lco/touchlab/squeaky/dao/ModelDao<Lcom/kgalligan/partyclicker/data/Person;>;Ljava/lang/String;)V", "()Lco/touchlab/squeaky/table/TableInfo<Lcom/kgalligan/partyclicker/data/Person;>;", &PDPerson_Configuration_instance, "LPDPerson_Configuration_Fields;", "Ljava/lang/Object;Lco/touchlab/squeaky/table/GeneratedTableMapper<Lcom/kgalligan/partyclicker/data/Person;>;" };
  static const J2ObjcClassInfo _PDPerson_Configuration = { "Person$Configuration", "com.kgalligan.partyclicker.data", ptrTable, methods, fields, 7, 0x11, 13, 3, -1, 21, -1, 22, -1 };
  return &_PDPerson_Configuration;
}

+ (void)initialize {
  if (self == [PDPerson_Configuration class]) {
    JreStrongAssignAndConsume(&PDPerson_Configuration_instance, new_PDPerson_Configuration_init());
    J2OBJC_SET_INITIALIZED(PDPerson_Configuration)
  }
}

@end

void PDPerson_Configuration_init(PDPerson_Configuration *self) {
  NSObject_init(self);
  JreStrongAssign(&self->fields_, PDPerson_Configuration_getFields());
  JreStrongAssign(&self->foreignConfigs_, PDPerson_Configuration_getForeignConfigs());
}

PDPerson_Configuration *new_PDPerson_Configuration_init() {
  J2OBJC_NEW_IMPL(PDPerson_Configuration, init)
}

PDPerson_Configuration *create_PDPerson_Configuration_init() {
  J2OBJC_CREATE_IMPL(PDPerson_Configuration, init)
}

IOSObjectArray *PDPerson_Configuration_getFields() {
  PDPerson_Configuration_initialize();
  return PDPerson_Configuration_Fields_values();
}

IOSObjectArray *PDPerson_Configuration_getForeignConfigs() {
  PDPerson_Configuration_initialize();
  id<JavaUtilList> list = create_JavaUtilArrayList_init();
  CoTouchlabSqueakyFieldForeignCollectionInfo *config = nil;
  return [list toArrayWithNSObjectArray:[IOSObjectArray arrayWithLength:[list size] type:CoTouchlabSqueakyFieldForeignCollectionInfo_class_()]];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(PDPerson_Configuration)

J2OBJC_INITIALIZED_DEFN(PDPerson_Configuration_Fields)

PDPerson_Configuration_Fields *PDPerson_Configuration_Fields_values_[4];

@implementation PDPerson_Configuration_Fields

- (CoTouchlabSqueakyFieldFieldType *)getFieldType {
  return fieldType_;
}

+ (IOSObjectArray *)values {
  return PDPerson_Configuration_Fields_values();
}

+ (PDPerson_Configuration_Fields *)valueOfWithNSString:(NSString *)name {
  return PDPerson_Configuration_Fields_valueOfWithNSString_(name);
}

- (id)copyWithZone:(NSZone *)zone {
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LCoTouchlabSqueakyFieldFieldType;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "[LPDPerson_Configuration_Fields;", 0x9, -1, -1, -1, -1, -1, -1 },
    { NULL, "LPDPerson_Configuration_Fields;", 0x9, 0, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(getFieldType);
  methods[1].selector = @selector(values);
  methods[2].selector = @selector(valueOfWithNSString:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "id", "LPDPerson_Configuration_Fields;", .constantValue.asLong = 0, 0x4019, -1, 2, -1, -1 },
    { "recorded", "LPDPerson_Configuration_Fields;", .constantValue.asLong = 0, 0x4019, -1, 3, -1, -1 },
    { "val", "LPDPerson_Configuration_Fields;", .constantValue.asLong = 0, 0x4019, -1, 4, -1, -1 },
    { "party", "LPDPerson_Configuration_Fields;", .constantValue.asLong = 0, 0x4019, -1, 5, -1, -1 },
    { "fieldType_", "LCoTouchlabSqueakyFieldFieldType;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "valueOf", "LNSString;", &JreEnum(PDPerson_Configuration_Fields, id), &JreEnum(PDPerson_Configuration_Fields, recorded), &JreEnum(PDPerson_Configuration_Fields, val), &JreEnum(PDPerson_Configuration_Fields, party), "LPDPerson_Configuration;", "Ljava/lang/Enum<Lcom/kgalligan/partyclicker/data/Person$Configuration$Fields;>;Lco/touchlab/squeaky/field/FieldsEnum;" };
  static const J2ObjcClassInfo _PDPerson_Configuration_Fields = { "Fields", "com.kgalligan.partyclicker.data", ptrTable, methods, fields, 7, 0x4019, 3, 5, 6, -1, -1, 7, -1 };
  return &_PDPerson_Configuration_Fields;
}

+ (void)initialize {
  if (self == [PDPerson_Configuration_Fields class]) {
    size_t objSize = class_getInstanceSize(self);
    size_t allocSize = 4 * objSize;
    uintptr_t ptr = (uintptr_t)calloc(allocSize, 1);
    id e;
    (JreEnum(PDPerson_Configuration_Fields, id) = e = objc_constructInstance(self, (void *)ptr), ptr += objSize);
    PDPerson_Configuration_Fields_initWithCoTouchlabSqueakyFieldFieldType_withNSString_withInt_(e, create_CoTouchlabSqueakyFieldFieldType_initWithNSString_withNSString_withNSString_withBoolean_withBoolean_withBoolean_withCoTouchlabSqueakyFieldDataType_withIOSClass_withBoolean_withNSString_withBoolean_withBoolean_withBoolean_withBoolean_withNSString_withNSString_withNSString_withBoolean_(@"person", @"id", @"id", true, true, false, JreLoadEnum(CoTouchlabSqueakyFieldDataType, INTEGER), [IOSClass intClass], true, nil, false, false, false, false, nil, nil, nil, false), @"id", 0);
    (JreEnum(PDPerson_Configuration_Fields, recorded) = e = objc_constructInstance(self, (void *)ptr), ptr += objSize);
    PDPerson_Configuration_Fields_initWithCoTouchlabSqueakyFieldFieldType_withNSString_withInt_(e, create_CoTouchlabSqueakyFieldFieldType_initWithNSString_withNSString_withNSString_withBoolean_withBoolean_withBoolean_withCoTouchlabSqueakyFieldDataType_withIOSClass_withBoolean_withNSString_withBoolean_withBoolean_withBoolean_withBoolean_withNSString_withNSString_withNSString_withBoolean_(@"person", @"recorded", @"recorded", false, false, false, JreLoadEnum(CoTouchlabSqueakyFieldDataType, DATE_LONG), JavaUtilDate_class_(), true, nil, false, false, false, false, nil, nil, nil, false), @"recorded", 1);
    (JreEnum(PDPerson_Configuration_Fields, val) = e = objc_constructInstance(self, (void *)ptr), ptr += objSize);
    PDPerson_Configuration_Fields_initWithCoTouchlabSqueakyFieldFieldType_withNSString_withInt_(e, create_CoTouchlabSqueakyFieldFieldType_initWithNSString_withNSString_withNSString_withBoolean_withBoolean_withBoolean_withCoTouchlabSqueakyFieldDataType_withIOSClass_withBoolean_withNSString_withBoolean_withBoolean_withBoolean_withBoolean_withNSString_withNSString_withNSString_withBoolean_(@"person", @"val", @"val", false, false, false, JreLoadEnum(CoTouchlabSqueakyFieldDataType, SHORT), [IOSClass shortClass], true, nil, false, false, false, false, nil, nil, nil, false), @"val", 2);
    (JreEnum(PDPerson_Configuration_Fields, party) = e = objc_constructInstance(self, (void *)ptr), ptr += objSize);
    PDPerson_Configuration_Fields_initWithCoTouchlabSqueakyFieldFieldType_withNSString_withInt_(e, create_CoTouchlabSqueakyFieldFieldType_initWithNSString_withNSString_withNSString_withBoolean_withBoolean_withBoolean_withCoTouchlabSqueakyFieldDataType_withIOSClass_withBoolean_withNSString_withBoolean_withBoolean_withBoolean_withBoolean_withNSString_withNSString_withNSString_withBoolean_(@"person", @"party", @"party_id", false, false, true, JreLoadEnum(CoTouchlabSqueakyFieldDataType, INTEGER), PDParty_class_(), true, nil, false, false, false, false, nil, nil, nil, true), @"party", 3);
    J2OBJC_SET_INITIALIZED(PDPerson_Configuration_Fields)
  }
}

@end

void PDPerson_Configuration_Fields_initWithCoTouchlabSqueakyFieldFieldType_withNSString_withInt_(PDPerson_Configuration_Fields *self, CoTouchlabSqueakyFieldFieldType *fieldType, NSString *__name, jint __ordinal) {
  JavaLangEnum_initWithNSString_withInt_(self, __name, __ordinal);
  JreStrongAssign(&self->fieldType_, fieldType);
}

IOSObjectArray *PDPerson_Configuration_Fields_values() {
  PDPerson_Configuration_Fields_initialize();
  return [IOSObjectArray arrayWithObjects:PDPerson_Configuration_Fields_values_ count:4 type:PDPerson_Configuration_Fields_class_()];
}

PDPerson_Configuration_Fields *PDPerson_Configuration_Fields_valueOfWithNSString_(NSString *name) {
  PDPerson_Configuration_Fields_initialize();
  for (int i = 0; i < 4; i++) {
    PDPerson_Configuration_Fields *e = PDPerson_Configuration_Fields_values_[i];
    if ([name isEqual:[e name]]) {
      return e;
    }
  }
  @throw create_JavaLangIllegalArgumentException_initWithNSString_(name);
  return nil;
}

PDPerson_Configuration_Fields *PDPerson_Configuration_Fields_fromOrdinal(NSUInteger ordinal) {
  PDPerson_Configuration_Fields_initialize();
  if (ordinal >= 4) {
    return nil;
  }
  return PDPerson_Configuration_Fields_values_[ordinal];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(PDPerson_Configuration_Fields)
