//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_PPCrashReporter")
#ifdef RESTRICT_PPCrashReporter
#define INCLUDE_ALL_PPCrashReporter 0
#else
#define INCLUDE_ALL_PPCrashReporter 1
#endif
#undef RESTRICT_PPCrashReporter

#if !defined (PPCrashReporter_) && (INCLUDE_ALL_PPCrashReporter || defined(INCLUDE_PPCrashReporter))
#define PPCrashReporter_

@protocol PPCrashReporter < JavaObject >

- (void)logWithNSString:(NSString *)s;

- (void)reportWithNSException:(NSException *)t;

@end

J2OBJC_EMPTY_STATIC_INIT(PPCrashReporter)

J2OBJC_TYPE_LITERAL_HEADER(PPCrashReporter)

#define ComKgalliganPartyclickerPresenterCrashReporter PPCrashReporter

#endif

#pragma pop_macro("INCLUDE_ALL_PPCrashReporter")
