//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_PPDaggerDaggerComponent")
#ifdef RESTRICT_PPDaggerDaggerComponent
#define INCLUDE_ALL_PPDaggerDaggerComponent 0
#else
#define INCLUDE_ALL_PPDaggerDaggerComponent 1
#endif
#undef RESTRICT_PPDaggerDaggerComponent

#if !defined (PPDaggerDaggerComponent_) && (INCLUDE_ALL_PPDaggerDaggerComponent || defined(INCLUDE_PPDaggerDaggerComponent))
#define PPDaggerDaggerComponent_

#define RESTRICT_PPDaggerComponent 1
#define INCLUDE_PPDaggerComponent 1
#include "PPDaggerComponent.h"

@class PPDaggerDaggerComponent_Builder;
@class PPPartyListPresenter;
@class PPPartyPresenter;

@interface PPDaggerDaggerComponent : NSObject < PPDaggerComponent >

#pragma mark Public

+ (PPDaggerDaggerComponent_Builder *)builder;

- (void)injectWithPPPartyListPresenter:(PPPartyListPresenter *)presenter;

- (void)injectWithPPPartyPresenter:(PPPartyPresenter *)presenter;

@end

J2OBJC_EMPTY_STATIC_INIT(PPDaggerDaggerComponent)

FOUNDATION_EXPORT PPDaggerDaggerComponent_Builder *PPDaggerDaggerComponent_builder();

J2OBJC_TYPE_LITERAL_HEADER(PPDaggerDaggerComponent)

@compatibility_alias ComKgalliganPartyclickerPresenterDaggerDaggerComponent PPDaggerDaggerComponent;

#endif

#if !defined (PPDaggerDaggerComponent_Builder_) && (INCLUDE_ALL_PPDaggerDaggerComponent || defined(INCLUDE_PPDaggerDaggerComponent_Builder))
#define PPDaggerDaggerComponent_Builder_

@class PPAppModule;
@protocol PPDaggerComponent;

@interface PPDaggerDaggerComponent_Builder : NSObject

#pragma mark Public

- (PPDaggerDaggerComponent_Builder *)appModuleWithPPAppModule:(PPAppModule *)appModule;

- (id<PPDaggerComponent>)build;

@end

J2OBJC_EMPTY_STATIC_INIT(PPDaggerDaggerComponent_Builder)

J2OBJC_TYPE_LITERAL_HEADER(PPDaggerDaggerComponent_Builder)

#endif

#pragma pop_macro("INCLUDE_ALL_PPDaggerDaggerComponent")
