//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/dagger/core/src/main/java/dagger/internal/MembersInjectors.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_DaggerInternalMembersInjectors")
#ifdef RESTRICT_DaggerInternalMembersInjectors
#define INCLUDE_ALL_DaggerInternalMembersInjectors 0
#else
#define INCLUDE_ALL_DaggerInternalMembersInjectors 1
#endif
#undef RESTRICT_DaggerInternalMembersInjectors

#if !defined (DaggerInternalMembersInjectors_) && (INCLUDE_ALL_DaggerInternalMembersInjectors || defined(INCLUDE_DaggerInternalMembersInjectors))
#define DaggerInternalMembersInjectors_

@protocol DaggerMembersInjector;

@interface DaggerInternalMembersInjectors : NSObject

#pragma mark Public

+ (id<DaggerMembersInjector>)delegatingToWithDaggerMembersInjector:(id<DaggerMembersInjector>)delegate;

+ (id)injectMembersWithDaggerMembersInjector:(id<DaggerMembersInjector>)membersInjector
                                      withId:(id)instance;

+ (id<DaggerMembersInjector>)noOp;

@end

J2OBJC_EMPTY_STATIC_INIT(DaggerInternalMembersInjectors)

FOUNDATION_EXPORT id DaggerInternalMembersInjectors_injectMembersWithDaggerMembersInjector_withId_(id<DaggerMembersInjector> membersInjector, id instance);

FOUNDATION_EXPORT id<DaggerMembersInjector> DaggerInternalMembersInjectors_noOp();

FOUNDATION_EXPORT id<DaggerMembersInjector> DaggerInternalMembersInjectors_delegatingToWithDaggerMembersInjector_(id<DaggerMembersInjector> delegate);

J2OBJC_TYPE_LITERAL_HEADER(DaggerInternalMembersInjectors)

#endif

#pragma pop_macro("INCLUDE_ALL_DaggerInternalMembersInjectors")
