//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_PPPartyListPresenterTest")
#ifdef RESTRICT_PPPartyListPresenterTest
#define INCLUDE_ALL_PPPartyListPresenterTest 0
#else
#define INCLUDE_ALL_PPPartyListPresenterTest 1
#endif
#undef RESTRICT_PPPartyListPresenterTest

#if !defined (PPPartyListPresenterTest_) && (INCLUDE_ALL_PPPartyListPresenterTest || defined(INCLUDE_PPPartyListPresenterTest))
#define PPPartyListPresenterTest_

@protocol PDDataProvider;

@interface PPPartyListPresenterTest : NSObject {
 @public
  id<PDDataProvider> dataProvider_;
}

#pragma mark Public

- (instancetype)init;

- (void)allPeople;

- (void)callParty;

- (void)callRefreshPartyList;

- (void)countPeople;

- (void)createParty;

- (void)deleteParty;

- (void)setUp;

@end

J2OBJC_EMPTY_STATIC_INIT(PPPartyListPresenterTest)

J2OBJC_FIELD_SETTER(PPPartyListPresenterTest, dataProvider_, id<PDDataProvider>)

FOUNDATION_EXPORT void PPPartyListPresenterTest_init(PPPartyListPresenterTest *self);

FOUNDATION_EXPORT PPPartyListPresenterTest *new_PPPartyListPresenterTest_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT PPPartyListPresenterTest *create_PPPartyListPresenterTest_init();

J2OBJC_TYPE_LITERAL_HEADER(PPPartyListPresenterTest)

@compatibility_alias ComKgalliganPartyclickerPresenterPartyListPresenterTest PPPartyListPresenterTest;

#endif

#pragma pop_macro("INCLUDE_ALL_PPPartyListPresenterTest")
