//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_PPPartyListPresenterTest_MembersInjector")
#ifdef RESTRICT_PPPartyListPresenterTest_MembersInjector
#define INCLUDE_ALL_PPPartyListPresenterTest_MembersInjector 0
#else
#define INCLUDE_ALL_PPPartyListPresenterTest_MembersInjector 1
#endif
#undef RESTRICT_PPPartyListPresenterTest_MembersInjector

#if !defined (PPPartyListPresenterTest_MembersInjector_) && (INCLUDE_ALL_PPPartyListPresenterTest_MembersInjector || defined(INCLUDE_PPPartyListPresenterTest_MembersInjector))
#define PPPartyListPresenterTest_MembersInjector_

#define RESTRICT_DaggerMembersInjector 1
#define INCLUDE_DaggerMembersInjector 1
#include "DaggerMembersInjector.h"

@class PPPartyListPresenterTest;
@protocol JavaxInjectProvider;

@interface PPPartyListPresenterTest_MembersInjector : NSObject < DaggerMembersInjector >

#pragma mark Public

- (instancetype)initWithJavaxInjectProvider:(id<JavaxInjectProvider>)dataProvider;

+ (id<DaggerMembersInjector>)createWithJavaxInjectProvider:(id<JavaxInjectProvider>)dataProvider;

+ (void)injectDataProviderWithPPPartyListPresenterTest:(PPPartyListPresenterTest *)instance
                               withJavaxInjectProvider:(id<JavaxInjectProvider>)dataProvider;

- (void)injectMembersWithId:(PPPartyListPresenterTest *)instance;

@end

J2OBJC_EMPTY_STATIC_INIT(PPPartyListPresenterTest_MembersInjector)

FOUNDATION_EXPORT void PPPartyListPresenterTest_MembersInjector_initWithJavaxInjectProvider_(PPPartyListPresenterTest_MembersInjector *self, id<JavaxInjectProvider> dataProvider);

FOUNDATION_EXPORT PPPartyListPresenterTest_MembersInjector *new_PPPartyListPresenterTest_MembersInjector_initWithJavaxInjectProvider_(id<JavaxInjectProvider> dataProvider) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT PPPartyListPresenterTest_MembersInjector *create_PPPartyListPresenterTest_MembersInjector_initWithJavaxInjectProvider_(id<JavaxInjectProvider> dataProvider);

FOUNDATION_EXPORT id<DaggerMembersInjector> PPPartyListPresenterTest_MembersInjector_createWithJavaxInjectProvider_(id<JavaxInjectProvider> dataProvider);

FOUNDATION_EXPORT void PPPartyListPresenterTest_MembersInjector_injectDataProviderWithPPPartyListPresenterTest_withJavaxInjectProvider_(PPPartyListPresenterTest *instance, id<JavaxInjectProvider> dataProvider);

J2OBJC_TYPE_LITERAL_HEADER(PPPartyListPresenterTest_MembersInjector)

@compatibility_alias ComKgalliganPartyclickerPresenterPartyListPresenterTest_MembersInjector PPPartyListPresenterTest_MembersInjector;

#endif

#pragma pop_macro("INCLUDE_ALL_PPPartyListPresenterTest_MembersInjector")
