//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "DaggerInternalFactory.h"
#include "DaggerInternalPreconditions.h"
#include "J2ObjC_source.h"
#include "PDDataProvider.h"
#include "PDPartyDatabase.h"
#include "PTTestAppModule.h"
#include "PTTestAppModule_ProvidesDataProviderFactory.h"
#include "javax/inject/Provider.h"

@interface PTTestAppModule_ProvidesDataProviderFactory () {
 @public
  PTTestAppModule *module_;
  id<JavaxInjectProvider> partyDatabaseProvider_;
}

@end

J2OBJC_FIELD_SETTER(PTTestAppModule_ProvidesDataProviderFactory, module_, PTTestAppModule *)
J2OBJC_FIELD_SETTER(PTTestAppModule_ProvidesDataProviderFactory, partyDatabaseProvider_, id<JavaxInjectProvider>)

@implementation PTTestAppModule_ProvidesDataProviderFactory

- (instancetype)initWithPTTestAppModule:(PTTestAppModule *)module
                withJavaxInjectProvider:(id<JavaxInjectProvider>)partyDatabaseProvider {
  PTTestAppModule_ProvidesDataProviderFactory_initWithPTTestAppModule_withJavaxInjectProvider_(self, module, partyDatabaseProvider);
  return self;
}

- (id<PDDataProvider>)get {
  return DaggerInternalPreconditions_checkNotNullWithId_withNSString_([((PTTestAppModule *) nil_chk(module_)) providesDataProviderWithPDPartyDatabase:[((id<JavaxInjectProvider>) nil_chk(partyDatabaseProvider_)) get]], @"Cannot return null from a non-@Nullable @Provides method");
}

+ (id<DaggerInternalFactory>)createWithPTTestAppModule:(PTTestAppModule *)module
                               withJavaxInjectProvider:(id<JavaxInjectProvider>)partyDatabaseProvider {
  return PTTestAppModule_ProvidesDataProviderFactory_createWithPTTestAppModule_withJavaxInjectProvider_(module, partyDatabaseProvider);
}

- (void)dealloc {
  RELEASE_(module_);
  RELEASE_(partyDatabaseProvider_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, 1, -1, -1 },
    { NULL, "LPDDataProvider;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LDaggerInternalFactory;", 0x9, 2, 0, -1, 3, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithPTTestAppModule:withJavaxInjectProvider:);
  methods[1].selector = @selector(get);
  methods[2].selector = @selector(createWithPTTestAppModule:withJavaxInjectProvider:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "module_", "LPTTestAppModule;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "partyDatabaseProvider_", "LJavaxInjectProvider;", .constantValue.asLong = 0, 0x12, -1, -1, 4, -1 },
  };
  static const void *ptrTable[] = { "LPTTestAppModule;LJavaxInjectProvider;", "(Lcom/kgalligan/partyclicker/test/TestAppModule;Ljavax/inject/Provider<Lcom/kgalligan/partyclicker/data/PartyDatabase;>;)V", "create", "(Lcom/kgalligan/partyclicker/test/TestAppModule;Ljavax/inject/Provider<Lcom/kgalligan/partyclicker/data/PartyDatabase;>;)Ldagger/internal/Factory<Lcom/kgalligan/partyclicker/data/DataProvider;>;", "Ljavax/inject/Provider<Lcom/kgalligan/partyclicker/data/PartyDatabase;>;", "Ljava/lang/Object;Ldagger/internal/Factory<Lcom/kgalligan/partyclicker/data/DataProvider;>;" };
  static const J2ObjcClassInfo _PTTestAppModule_ProvidesDataProviderFactory = { "TestAppModule_ProvidesDataProviderFactory", "com.kgalligan.partyclicker.test", ptrTable, methods, fields, 7, 0x11, 3, 2, -1, -1, -1, 5, -1 };
  return &_PTTestAppModule_ProvidesDataProviderFactory;
}

@end

void PTTestAppModule_ProvidesDataProviderFactory_initWithPTTestAppModule_withJavaxInjectProvider_(PTTestAppModule_ProvidesDataProviderFactory *self, PTTestAppModule *module, id<JavaxInjectProvider> partyDatabaseProvider) {
  NSObject_init(self);
  JreAssert((module != nil), (@"com/kgalligan/partyclicker/test/TestAppModule_ProvidesDataProviderFactory.java:21 condition failed: assert module != null;"));
  JreStrongAssign(&self->module_, module);
  JreAssert((partyDatabaseProvider != nil), (@"com/kgalligan/partyclicker/test/TestAppModule_ProvidesDataProviderFactory.java:23 condition failed: assert partyDatabaseProvider != null;"));
  JreStrongAssign(&self->partyDatabaseProvider_, partyDatabaseProvider);
}

PTTestAppModule_ProvidesDataProviderFactory *new_PTTestAppModule_ProvidesDataProviderFactory_initWithPTTestAppModule_withJavaxInjectProvider_(PTTestAppModule *module, id<JavaxInjectProvider> partyDatabaseProvider) {
  J2OBJC_NEW_IMPL(PTTestAppModule_ProvidesDataProviderFactory, initWithPTTestAppModule_withJavaxInjectProvider_, module, partyDatabaseProvider)
}

PTTestAppModule_ProvidesDataProviderFactory *create_PTTestAppModule_ProvidesDataProviderFactory_initWithPTTestAppModule_withJavaxInjectProvider_(PTTestAppModule *module, id<JavaxInjectProvider> partyDatabaseProvider) {
  J2OBJC_CREATE_IMPL(PTTestAppModule_ProvidesDataProviderFactory, initWithPTTestAppModule_withJavaxInjectProvider_, module, partyDatabaseProvider)
}

id<DaggerInternalFactory> PTTestAppModule_ProvidesDataProviderFactory_createWithPTTestAppModule_withJavaxInjectProvider_(PTTestAppModule *module, id<JavaxInjectProvider> partyDatabaseProvider) {
  PTTestAppModule_ProvidesDataProviderFactory_initialize();
  return create_PTTestAppModule_ProvidesDataProviderFactory_initWithPTTestAppModule_withJavaxInjectProvider_(module, partyDatabaseProvider);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(PTTestAppModule_ProvidesDataProviderFactory)
