//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComKgalliganPartyclickerDataModPersonTask")
#ifdef RESTRICT_ComKgalliganPartyclickerDataModPersonTask
#define INCLUDE_ALL_ComKgalliganPartyclickerDataModPersonTask 0
#else
#define INCLUDE_ALL_ComKgalliganPartyclickerDataModPersonTask 1
#endif
#undef RESTRICT_ComKgalliganPartyclickerDataModPersonTask

#if !defined (ComKgalliganPartyclickerDataModPersonTask_) && (INCLUDE_ALL_ComKgalliganPartyclickerDataModPersonTask || defined(INCLUDE_ComKgalliganPartyclickerDataModPersonTask))
#define ComKgalliganPartyclickerDataModPersonTask_

#define RESTRICT_JavaLangRunnable 1
#define INCLUDE_JavaLangRunnable 1
#include "java/lang/Runnable.h"

@class ComKgalliganPartyclickerDataDatabaseHelper;
@class ComKgalliganPartyclickerDataParty;

@interface ComKgalliganPartyclickerDataModPersonTask : NSObject < JavaLangRunnable >

#pragma mark Public

- (instancetype)initWithComKgalliganPartyclickerDataParty:(ComKgalliganPartyclickerDataParty *)party
                                              withBoolean:(jboolean)coming
           withComKgalliganPartyclickerDataDatabaseHelper:(ComKgalliganPartyclickerDataDatabaseHelper *)databaseHelper;

- (void)run;

@end

J2OBJC_EMPTY_STATIC_INIT(ComKgalliganPartyclickerDataModPersonTask)

FOUNDATION_EXPORT void ComKgalliganPartyclickerDataModPersonTask_initWithComKgalliganPartyclickerDataParty_withBoolean_withComKgalliganPartyclickerDataDatabaseHelper_(ComKgalliganPartyclickerDataModPersonTask *self, ComKgalliganPartyclickerDataParty *party, jboolean coming, ComKgalliganPartyclickerDataDatabaseHelper *databaseHelper);

FOUNDATION_EXPORT ComKgalliganPartyclickerDataModPersonTask *new_ComKgalliganPartyclickerDataModPersonTask_initWithComKgalliganPartyclickerDataParty_withBoolean_withComKgalliganPartyclickerDataDatabaseHelper_(ComKgalliganPartyclickerDataParty *party, jboolean coming, ComKgalliganPartyclickerDataDatabaseHelper *databaseHelper) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComKgalliganPartyclickerDataModPersonTask *create_ComKgalliganPartyclickerDataModPersonTask_initWithComKgalliganPartyclickerDataParty_withBoolean_withComKgalliganPartyclickerDataDatabaseHelper_(ComKgalliganPartyclickerDataParty *party, jboolean coming, ComKgalliganPartyclickerDataDatabaseHelper *databaseHelper);

J2OBJC_TYPE_LITERAL_HEADER(ComKgalliganPartyclickerDataModPersonTask)

#endif

#pragma pop_macro("INCLUDE_ALL_ComKgalliganPartyclickerDataModPersonTask")
