//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/PartyClicker/app/src/main/java/com/kgalligan/partyclicker/data/PartyPresenter.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComKgalliganPartyclickerDataPartyPresenter")
#ifdef RESTRICT_ComKgalliganPartyclickerDataPartyPresenter
#define INCLUDE_ALL_ComKgalliganPartyclickerDataPartyPresenter 0
#else
#define INCLUDE_ALL_ComKgalliganPartyclickerDataPartyPresenter 1
#endif
#undef RESTRICT_ComKgalliganPartyclickerDataPartyPresenter

#if !defined (ComKgalliganPartyclickerDataPartyPresenter_) && (INCLUDE_ALL_ComKgalliganPartyclickerDataPartyPresenter || defined(INCLUDE_ComKgalliganPartyclickerDataPartyPresenter))
#define ComKgalliganPartyclickerDataPartyPresenter_

@class ComKgalliganPartyclickerDataParty;

@interface ComKgalliganPartyclickerDataPartyPresenter : NSObject

#pragma mark Public

- (instancetype)initWithInt:(jint)partyId;

- (void)addPerson;

- (ComKgalliganPartyclickerDataParty *)getParty;

- (jint)getPartyCount;

- (void)removePerson;

@end

J2OBJC_EMPTY_STATIC_INIT(ComKgalliganPartyclickerDataPartyPresenter)

FOUNDATION_EXPORT void ComKgalliganPartyclickerDataPartyPresenter_initWithInt_(ComKgalliganPartyclickerDataPartyPresenter *self, jint partyId);

FOUNDATION_EXPORT ComKgalliganPartyclickerDataPartyPresenter *new_ComKgalliganPartyclickerDataPartyPresenter_initWithInt_(jint partyId) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComKgalliganPartyclickerDataPartyPresenter *create_ComKgalliganPartyclickerDataPartyPresenter_initWithInt_(jint partyId);

J2OBJC_TYPE_LITERAL_HEADER(ComKgalliganPartyclickerDataPartyPresenter)

#endif

#pragma pop_macro("INCLUDE_ALL_ComKgalliganPartyclickerDataPartyPresenter")
