//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "ComKgalliganPartyclickerDataDatabaseHelper.h"
#include "ComKgalliganPartyclickerPresenterPartyListPresenter.h"
#include "ComKgalliganPartyclickerPresenterPartyListPresenter_MembersInjector.h"
#include "DaggerMembersInjector.h"
#include "J2ObjC_source.h"
#include "java/lang/NullPointerException.h"
#include "javax/inject/Provider.h"

@interface ComKgalliganPartyclickerPresenterPartyListPresenter_MembersInjector () {
 @public
  id<JavaxInjectProvider> databaseHelperProvider_;
}

@end

J2OBJC_FIELD_SETTER(ComKgalliganPartyclickerPresenterPartyListPresenter_MembersInjector, databaseHelperProvider_, id<JavaxInjectProvider>)

@implementation ComKgalliganPartyclickerPresenterPartyListPresenter_MembersInjector

- (instancetype)initWithJavaxInjectProvider:(id<JavaxInjectProvider>)databaseHelperProvider {
  ComKgalliganPartyclickerPresenterPartyListPresenter_MembersInjector_initWithJavaxInjectProvider_(self, databaseHelperProvider);
  return self;
}

+ (id<DaggerMembersInjector>)createWithJavaxInjectProvider:(id<JavaxInjectProvider>)databaseHelperProvider {
  return ComKgalliganPartyclickerPresenterPartyListPresenter_MembersInjector_createWithJavaxInjectProvider_(databaseHelperProvider);
}

- (void)injectMembersWithId:(ComKgalliganPartyclickerPresenterPartyListPresenter *)instance {
  if (instance == nil) {
    @throw create_JavaLangNullPointerException_initWithNSString_(@"Cannot inject members into a null reference");
  }
  JreStrongAssign(&instance->databaseHelper_, [((id<JavaxInjectProvider>) nil_chk(databaseHelperProvider_)) get]);
}

+ (void)injectDatabaseHelperWithComKgalliganPartyclickerPresenterPartyListPresenter:(ComKgalliganPartyclickerPresenterPartyListPresenter *)instance
                                                            withJavaxInjectProvider:(id<JavaxInjectProvider>)databaseHelperProvider {
  ComKgalliganPartyclickerPresenterPartyListPresenter_MembersInjector_injectDatabaseHelperWithComKgalliganPartyclickerPresenterPartyListPresenter_withJavaxInjectProvider_(instance, databaseHelperProvider);
}

- (void)dealloc {
  RELEASE_(databaseHelperProvider_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, 1, -1, -1 },
    { NULL, "LDaggerMembersInjector;", 0x9, 2, 0, -1, 3, -1, -1 },
    { NULL, "V", 0x1, 4, 5, -1, -1, -1, -1 },
    { NULL, "V", 0x9, 6, 7, -1, 8, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithJavaxInjectProvider:);
  methods[1].selector = @selector(createWithJavaxInjectProvider:);
  methods[2].selector = @selector(injectMembersWithId:);
  methods[3].selector = @selector(injectDatabaseHelperWithComKgalliganPartyclickerPresenterPartyListPresenter:withJavaxInjectProvider:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "databaseHelperProvider_", "LJavaxInjectProvider;", .constantValue.asLong = 0, 0x12, -1, -1, 9, -1 },
  };
  static const void *ptrTable[] = { "LJavaxInjectProvider;", "(Ljavax/inject/Provider<Lcom/kgalligan/partyclicker/data/DatabaseHelper;>;)V", "create", "(Ljavax/inject/Provider<Lcom/kgalligan/partyclicker/data/DatabaseHelper;>;)Ldagger/MembersInjector<Lcom/kgalligan/partyclicker/presenter/PartyListPresenter;>;", "injectMembers", "LComKgalliganPartyclickerPresenterPartyListPresenter;", "injectDatabaseHelper", "LComKgalliganPartyclickerPresenterPartyListPresenter;LJavaxInjectProvider;", "(Lcom/kgalligan/partyclicker/presenter/PartyListPresenter;Ljavax/inject/Provider<Lcom/kgalligan/partyclicker/data/DatabaseHelper;>;)V", "Ljavax/inject/Provider<Lcom/kgalligan/partyclicker/data/DatabaseHelper;>;", "Ljava/lang/Object;Ldagger/MembersInjector<Lcom/kgalligan/partyclicker/presenter/PartyListPresenter;>;" };
  static const J2ObjcClassInfo _ComKgalliganPartyclickerPresenterPartyListPresenter_MembersInjector = { "PartyListPresenter_MembersInjector", "com.kgalligan.partyclicker.presenter", ptrTable, methods, fields, 7, 0x11, 4, 1, -1, -1, -1, 10, -1 };
  return &_ComKgalliganPartyclickerPresenterPartyListPresenter_MembersInjector;
}

@end

void ComKgalliganPartyclickerPresenterPartyListPresenter_MembersInjector_initWithJavaxInjectProvider_(ComKgalliganPartyclickerPresenterPartyListPresenter_MembersInjector *self, id<JavaxInjectProvider> databaseHelperProvider) {
  NSObject_init(self);
  JreAssert((databaseHelperProvider != nil), (@"com/kgalligan/partyclicker/presenter/PartyListPresenter_MembersInjector.java:13 condition failed: assert databaseHelperProvider != null;"));
  JreStrongAssign(&self->databaseHelperProvider_, databaseHelperProvider);
}

ComKgalliganPartyclickerPresenterPartyListPresenter_MembersInjector *new_ComKgalliganPartyclickerPresenterPartyListPresenter_MembersInjector_initWithJavaxInjectProvider_(id<JavaxInjectProvider> databaseHelperProvider) {
  J2OBJC_NEW_IMPL(ComKgalliganPartyclickerPresenterPartyListPresenter_MembersInjector, initWithJavaxInjectProvider_, databaseHelperProvider)
}

ComKgalliganPartyclickerPresenterPartyListPresenter_MembersInjector *create_ComKgalliganPartyclickerPresenterPartyListPresenter_MembersInjector_initWithJavaxInjectProvider_(id<JavaxInjectProvider> databaseHelperProvider) {
  J2OBJC_CREATE_IMPL(ComKgalliganPartyclickerPresenterPartyListPresenter_MembersInjector, initWithJavaxInjectProvider_, databaseHelperProvider)
}

id<DaggerMembersInjector> ComKgalliganPartyclickerPresenterPartyListPresenter_MembersInjector_createWithJavaxInjectProvider_(id<JavaxInjectProvider> databaseHelperProvider) {
  ComKgalliganPartyclickerPresenterPartyListPresenter_MembersInjector_initialize();
  return create_ComKgalliganPartyclickerPresenterPartyListPresenter_MembersInjector_initWithJavaxInjectProvider_(databaseHelperProvider);
}

void ComKgalliganPartyclickerPresenterPartyListPresenter_MembersInjector_injectDatabaseHelperWithComKgalliganPartyclickerPresenterPartyListPresenter_withJavaxInjectProvider_(ComKgalliganPartyclickerPresenterPartyListPresenter *instance, id<JavaxInjectProvider> databaseHelperProvider) {
  ComKgalliganPartyclickerPresenterPartyListPresenter_MembersInjector_initialize();
  JreStrongAssign(&((ComKgalliganPartyclickerPresenterPartyListPresenter *) nil_chk(instance))->databaseHelper_, [((id<JavaxInjectProvider>) nil_chk(databaseHelperProvider)) get]);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComKgalliganPartyclickerPresenterPartyListPresenter_MembersInjector)
