//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_PPAppModule_ProvidesSchedulerTransformerFactory")
#ifdef RESTRICT_PPAppModule_ProvidesSchedulerTransformerFactory
#define INCLUDE_ALL_PPAppModule_ProvidesSchedulerTransformerFactory 0
#else
#define INCLUDE_ALL_PPAppModule_ProvidesSchedulerTransformerFactory 1
#endif
#undef RESTRICT_PPAppModule_ProvidesSchedulerTransformerFactory

#if !defined (PPAppModule_ProvidesSchedulerTransformerFactory_) && (INCLUDE_ALL_PPAppModule_ProvidesSchedulerTransformerFactory || defined(INCLUDE_PPAppModule_ProvidesSchedulerTransformerFactory))
#define PPAppModule_ProvidesSchedulerTransformerFactory_

#define RESTRICT_DaggerInternalFactory 1
#define INCLUDE_DaggerInternalFactory 1
#include "DaggerInternalFactory.h"

@class PPAppModule;
@protocol RxObservable_Transformer;

@interface PPAppModule_ProvidesSchedulerTransformerFactory : NSObject < DaggerInternalFactory >

#pragma mark Public

- (instancetype)initWithPPAppModule:(PPAppModule *)module;

+ (id<DaggerInternalFactory>)createWithPPAppModule:(PPAppModule *)module;

- (id<RxObservable_Transformer>)get;

@end

J2OBJC_EMPTY_STATIC_INIT(PPAppModule_ProvidesSchedulerTransformerFactory)

FOUNDATION_EXPORT void PPAppModule_ProvidesSchedulerTransformerFactory_initWithPPAppModule_(PPAppModule_ProvidesSchedulerTransformerFactory *self, PPAppModule *module);

FOUNDATION_EXPORT PPAppModule_ProvidesSchedulerTransformerFactory *new_PPAppModule_ProvidesSchedulerTransformerFactory_initWithPPAppModule_(PPAppModule *module) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT PPAppModule_ProvidesSchedulerTransformerFactory *create_PPAppModule_ProvidesSchedulerTransformerFactory_initWithPPAppModule_(PPAppModule *module);

FOUNDATION_EXPORT id<DaggerInternalFactory> PPAppModule_ProvidesSchedulerTransformerFactory_createWithPPAppModule_(PPAppModule *module);

J2OBJC_TYPE_LITERAL_HEADER(PPAppModule_ProvidesSchedulerTransformerFactory)

@compatibility_alias ComKgalliganPartyclickerPresenterAppModule_ProvidesSchedulerTransformerFactory PPAppModule_ProvidesSchedulerTransformerFactory;

#endif

#pragma pop_macro("INCLUDE_ALL_PPAppModule_ProvidesSchedulerTransformerFactory")
