//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/PartyClicker/app/src/main/java/com/kgalligan/partyclicker/data/Party.java
//

#include "CoTouchlabSqueakyFieldDataType.h"
#include "CoTouchlabSqueakyFieldDatabaseField.h"
#include "CoTouchlabSqueakyFieldTypesVoidType.h"
#include "CoTouchlabSqueakyTableDatabaseTable.h"
#include "ComKgalliganPartyclickerDataParty.h"
#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "java/lang/annotation/Annotation.h"
#include "java/text/SimpleDateFormat.h"
#include "java/util/Date.h"

inline JavaTextSimpleDateFormat *ComKgalliganPartyclickerDataParty_get_timeFormat();
static JavaTextSimpleDateFormat *ComKgalliganPartyclickerDataParty_timeFormat;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComKgalliganPartyclickerDataParty, timeFormat, JavaTextSimpleDateFormat *)

__attribute__((unused)) static IOSObjectArray *ComKgalliganPartyclickerDataParty__Annotations$0();

__attribute__((unused)) static IOSObjectArray *ComKgalliganPartyclickerDataParty__Annotations$1();

__attribute__((unused)) static IOSObjectArray *ComKgalliganPartyclickerDataParty__Annotations$2();

__attribute__((unused)) static IOSObjectArray *ComKgalliganPartyclickerDataParty__Annotations$3();

J2OBJC_INITIALIZED_DEFN(ComKgalliganPartyclickerDataParty)

@implementation ComKgalliganPartyclickerDataParty

- (NSString *)description {
  return JreStrcat("$$$", name_, @" - ", [((JavaTextSimpleDateFormat *) nil_chk(ComKgalliganPartyclickerDataParty_timeFormat)) formatWithJavaUtilDate:created_]);
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComKgalliganPartyclickerDataParty_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (void)dealloc {
  RELEASE_(name_);
  RELEASE_(created_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LNSString;", 0x1, 0, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(description);
  methods[1].selector = @selector(init);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "timeFormat", "LJavaTextSimpleDateFormat;", .constantValue.asLong = 0, 0x1a, -1, 1, -1, -1 },
    { "id__", "I", .constantValue.asLong = 0, 0x1, 2, -1, -1, 3 },
    { "name_", "LNSString;", .constantValue.asLong = 0, 0x1, -1, -1, -1, 4 },
    { "created_", "LJavaUtilDate;", .constantValue.asLong = 0, 0x1, -1, -1, -1, 5 },
  };
  static const void *ptrTable[] = { "toString", &ComKgalliganPartyclickerDataParty_timeFormat, "id", (void *)&ComKgalliganPartyclickerDataParty__Annotations$0, (void *)&ComKgalliganPartyclickerDataParty__Annotations$1, (void *)&ComKgalliganPartyclickerDataParty__Annotations$2, (void *)&ComKgalliganPartyclickerDataParty__Annotations$3 };
  static const J2ObjcClassInfo _ComKgalliganPartyclickerDataParty = { "Party", "com.kgalligan.partyclicker.data", ptrTable, methods, fields, 7, 0x1, 2, 4, -1, -1, -1, -1, 6 };
  return &_ComKgalliganPartyclickerDataParty;
}

+ (void)initialize {
  if (self == [ComKgalliganPartyclickerDataParty class]) {
    JreStrongAssignAndConsume(&ComKgalliganPartyclickerDataParty_timeFormat, new_JavaTextSimpleDateFormat_initWithNSString_(@"MM/dd/yyyy hh:MM a"));
    J2OBJC_SET_INITIALIZED(ComKgalliganPartyclickerDataParty)
  }
}

@end

void ComKgalliganPartyclickerDataParty_init(ComKgalliganPartyclickerDataParty *self) {
  NSObject_init(self);
}

ComKgalliganPartyclickerDataParty *new_ComKgalliganPartyclickerDataParty_init() {
  J2OBJC_NEW_IMPL(ComKgalliganPartyclickerDataParty, init)
}

ComKgalliganPartyclickerDataParty *create_ComKgalliganPartyclickerDataParty_init() {
  J2OBJC_CREATE_IMPL(ComKgalliganPartyclickerDataParty, init)
}

IOSObjectArray *ComKgalliganPartyclickerDataParty__Annotations$0() {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_CoTouchlabSqueakyFieldDatabaseField(true, @"", JreLoadEnum(CoTouchlabSqueakyFieldDataType, UNKNOWN), @"__ormlite__ no default value string was specified", false, false, @"", true, false, false, @"", CoTouchlabSqueakyFieldTypesVoidType_class_(), false, false, false, @"", false) } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

IOSObjectArray *ComKgalliganPartyclickerDataParty__Annotations$1() {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_CoTouchlabSqueakyFieldDatabaseField(true, @"", JreLoadEnum(CoTouchlabSqueakyFieldDataType, UNKNOWN), @"__ormlite__ no default value string was specified", false, false, @"", false, false, false, @"", CoTouchlabSqueakyFieldTypesVoidType_class_(), false, false, false, @"", false) } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

IOSObjectArray *ComKgalliganPartyclickerDataParty__Annotations$2() {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_CoTouchlabSqueakyFieldDatabaseField(true, @"", JreLoadEnum(CoTouchlabSqueakyFieldDataType, DATE_LONG), @"__ormlite__ no default value string was specified", false, false, @"", false, false, false, @"", CoTouchlabSqueakyFieldTypesVoidType_class_(), false, false, false, @"", false) } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

IOSObjectArray *ComKgalliganPartyclickerDataParty__Annotations$3() {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_CoTouchlabSqueakyTableDatabaseTable(@"") } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComKgalliganPartyclickerDataParty)
