//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/PartyClicker/app/src/main/java/com/kgalligan/partyclicker/data/Person.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComKgalliganPartyclickerDataPerson")
#ifdef RESTRICT_ComKgalliganPartyclickerDataPerson
#define INCLUDE_ALL_ComKgalliganPartyclickerDataPerson 0
#else
#define INCLUDE_ALL_ComKgalliganPartyclickerDataPerson 1
#endif
#undef RESTRICT_ComKgalliganPartyclickerDataPerson

#if !defined (ComKgalliganPartyclickerDataPerson_) && (INCLUDE_ALL_ComKgalliganPartyclickerDataPerson || defined(INCLUDE_ComKgalliganPartyclickerDataPerson))
#define ComKgalliganPartyclickerDataPerson_

@class ComKgalliganPartyclickerDataParty;
@class JavaUtilDate;

@interface ComKgalliganPartyclickerDataPerson : NSObject {
 @public
  jint id__;
  JavaUtilDate *recorded_;
  jshort val_;
  ComKgalliganPartyclickerDataParty *party_;
}

#pragma mark Public

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ComKgalliganPartyclickerDataPerson)

J2OBJC_FIELD_SETTER(ComKgalliganPartyclickerDataPerson, recorded_, JavaUtilDate *)
J2OBJC_FIELD_SETTER(ComKgalliganPartyclickerDataPerson, party_, ComKgalliganPartyclickerDataParty *)

FOUNDATION_EXPORT void ComKgalliganPartyclickerDataPerson_init(ComKgalliganPartyclickerDataPerson *self);

FOUNDATION_EXPORT ComKgalliganPartyclickerDataPerson *new_ComKgalliganPartyclickerDataPerson_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComKgalliganPartyclickerDataPerson *create_ComKgalliganPartyclickerDataPerson_init();

J2OBJC_TYPE_LITERAL_HEADER(ComKgalliganPartyclickerDataPerson)

#endif

#pragma pop_macro("INCLUDE_ALL_ComKgalliganPartyclickerDataPerson")
