//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "CoTouchlabDopplTestingDopplJunitTestHelper.h"
#include "ComKgalliganPartyclickerDataDatabaseHelperTest.h"
#include "ComKgalliganPartyclickerDataModPersonTaskTest.h"
#include "ComKgalliganPartyclickerDataPartyPresenterTest.h"
#include "ComKgalliganPartyclickerPresenterPartyListPresenterTest.h"
#include "ComKgalliganPartyclickerTestIOSTestHelper.h"
#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"

@implementation ComKgalliganPartyclickerTestIOSTestHelper

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComKgalliganPartyclickerTestIOSTestHelper_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (jint)runTests {
  return ComKgalliganPartyclickerTestIOSTestHelper_runTests();
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x9, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(runTests);
  #pragma clang diagnostic pop
  static const J2ObjcClassInfo _ComKgalliganPartyclickerTestIOSTestHelper = { "IOSTestHelper", "com.kgalligan.partyclicker.test", NULL, methods, NULL, 7, 0x1, 2, 0, -1, -1, -1, -1, -1 };
  return &_ComKgalliganPartyclickerTestIOSTestHelper;
}

@end

void ComKgalliganPartyclickerTestIOSTestHelper_init(ComKgalliganPartyclickerTestIOSTestHelper *self) {
  NSObject_init(self);
}

ComKgalliganPartyclickerTestIOSTestHelper *new_ComKgalliganPartyclickerTestIOSTestHelper_init() {
  J2OBJC_NEW_IMPL(ComKgalliganPartyclickerTestIOSTestHelper, init)
}

ComKgalliganPartyclickerTestIOSTestHelper *create_ComKgalliganPartyclickerTestIOSTestHelper_init() {
  J2OBJC_CREATE_IMPL(ComKgalliganPartyclickerTestIOSTestHelper, init)
}

jint ComKgalliganPartyclickerTestIOSTestHelper_runTests() {
  ComKgalliganPartyclickerTestIOSTestHelper_initialize();
  return CoTouchlabDopplTestingDopplJunitTestHelper_runWithIOSClassArray_([IOSObjectArray arrayWithObjects:(id[]){ ComKgalliganPartyclickerDataDatabaseHelperTest_class_(), ComKgalliganPartyclickerDataModPersonTaskTest_class_(), ComKgalliganPartyclickerPresenterPartyListPresenterTest_class_(), ComKgalliganPartyclickerDataPartyPresenterTest_class_() } count:4 type:IOSClass_class_()]);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComKgalliganPartyclickerTestIOSTestHelper)
