//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "AndroidAppApplication.h"
#include "ComKgalliganPartyclickerTestTestAppModule.h"
#include "ComKgalliganPartyclickerTestTestAppModule_ProvidesApplicationFactory.h"
#include "DaggerInternalFactory.h"
#include "DaggerInternalPreconditions.h"
#include "J2ObjC_source.h"

@interface ComKgalliganPartyclickerTestTestAppModule_ProvidesApplicationFactory () {
 @public
  ComKgalliganPartyclickerTestTestAppModule *module_;
}

@end

J2OBJC_FIELD_SETTER(ComKgalliganPartyclickerTestTestAppModule_ProvidesApplicationFactory, module_, ComKgalliganPartyclickerTestTestAppModule *)

@implementation ComKgalliganPartyclickerTestTestAppModule_ProvidesApplicationFactory

- (instancetype)initWithComKgalliganPartyclickerTestTestAppModule:(ComKgalliganPartyclickerTestTestAppModule *)module {
  ComKgalliganPartyclickerTestTestAppModule_ProvidesApplicationFactory_initWithComKgalliganPartyclickerTestTestAppModule_(self, module);
  return self;
}

- (AndroidAppApplication *)get {
  return DaggerInternalPreconditions_checkNotNullWithId_withNSString_([((ComKgalliganPartyclickerTestTestAppModule *) nil_chk(module_)) providesApplication], @"Cannot return null from a non-@Nullable @Provides method");
}

+ (id<DaggerInternalFactory>)createWithComKgalliganPartyclickerTestTestAppModule:(ComKgalliganPartyclickerTestTestAppModule *)module {
  return ComKgalliganPartyclickerTestTestAppModule_ProvidesApplicationFactory_createWithComKgalliganPartyclickerTestTestAppModule_(module);
}

- (void)dealloc {
  RELEASE_(module_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "LAndroidAppApplication;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LDaggerInternalFactory;", 0x9, 1, 0, -1, 2, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithComKgalliganPartyclickerTestTestAppModule:);
  methods[1].selector = @selector(get);
  methods[2].selector = @selector(createWithComKgalliganPartyclickerTestTestAppModule:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "module_", "LComKgalliganPartyclickerTestTestAppModule;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LComKgalliganPartyclickerTestTestAppModule;", "create", "(Lcom/kgalligan/partyclicker/test/TestAppModule;)Ldagger/internal/Factory<Landroid/app/Application;>;", "Ljava/lang/Object;Ldagger/internal/Factory<Landroid/app/Application;>;" };
  static const J2ObjcClassInfo _ComKgalliganPartyclickerTestTestAppModule_ProvidesApplicationFactory = { "TestAppModule_ProvidesApplicationFactory", "com.kgalligan.partyclicker.test", ptrTable, methods, fields, 7, 0x11, 3, 1, -1, -1, -1, 3, -1 };
  return &_ComKgalliganPartyclickerTestTestAppModule_ProvidesApplicationFactory;
}

@end

void ComKgalliganPartyclickerTestTestAppModule_ProvidesApplicationFactory_initWithComKgalliganPartyclickerTestTestAppModule_(ComKgalliganPartyclickerTestTestAppModule_ProvidesApplicationFactory *self, ComKgalliganPartyclickerTestTestAppModule *module) {
  NSObject_init(self);
  JreAssert((module != nil), (@"com/kgalligan/partyclicker/test/TestAppModule_ProvidesApplicationFactory.java:16 condition failed: assert module != null;"));
  JreStrongAssign(&self->module_, module);
}

ComKgalliganPartyclickerTestTestAppModule_ProvidesApplicationFactory *new_ComKgalliganPartyclickerTestTestAppModule_ProvidesApplicationFactory_initWithComKgalliganPartyclickerTestTestAppModule_(ComKgalliganPartyclickerTestTestAppModule *module) {
  J2OBJC_NEW_IMPL(ComKgalliganPartyclickerTestTestAppModule_ProvidesApplicationFactory, initWithComKgalliganPartyclickerTestTestAppModule_, module)
}

ComKgalliganPartyclickerTestTestAppModule_ProvidesApplicationFactory *create_ComKgalliganPartyclickerTestTestAppModule_ProvidesApplicationFactory_initWithComKgalliganPartyclickerTestTestAppModule_(ComKgalliganPartyclickerTestTestAppModule *module) {
  J2OBJC_CREATE_IMPL(ComKgalliganPartyclickerTestTestAppModule_ProvidesApplicationFactory, initWithComKgalliganPartyclickerTestTestAppModule_, module)
}

id<DaggerInternalFactory> ComKgalliganPartyclickerTestTestAppModule_ProvidesApplicationFactory_createWithComKgalliganPartyclickerTestTestAppModule_(ComKgalliganPartyclickerTestTestAppModule *module) {
  ComKgalliganPartyclickerTestTestAppModule_ProvidesApplicationFactory_initialize();
  return create_ComKgalliganPartyclickerTestTestAppModule_ProvidesApplicationFactory_initWithComKgalliganPartyclickerTestTestAppModule_(module);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComKgalliganPartyclickerTestTestAppModule_ProvidesApplicationFactory)
