//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComKgalliganPartyclickerPresenterPartyListPresenterTest")
#ifdef RESTRICT_ComKgalliganPartyclickerPresenterPartyListPresenterTest
#define INCLUDE_ALL_ComKgalliganPartyclickerPresenterPartyListPresenterTest 0
#else
#define INCLUDE_ALL_ComKgalliganPartyclickerPresenterPartyListPresenterTest 1
#endif
#undef RESTRICT_ComKgalliganPartyclickerPresenterPartyListPresenterTest

#if !defined (ComKgalliganPartyclickerPresenterPartyListPresenterTest_) && (INCLUDE_ALL_ComKgalliganPartyclickerPresenterPartyListPresenterTest || defined(INCLUDE_ComKgalliganPartyclickerPresenterPartyListPresenterTest))
#define ComKgalliganPartyclickerPresenterPartyListPresenterTest_

@protocol ComKgalliganPartyclickerDataDataProvider;

@interface ComKgalliganPartyclickerPresenterPartyListPresenterTest : NSObject {
 @public
  id<ComKgalliganPartyclickerDataDataProvider> dataProvider_;
}

#pragma mark Public

- (instancetype)init;

- (void)allPeople;

- (void)callParty;

- (void)callRefreshPartyList;

- (void)countPeople;

- (void)createParty;

- (void)deleteParty;

- (void)setUp;

@end

J2OBJC_EMPTY_STATIC_INIT(ComKgalliganPartyclickerPresenterPartyListPresenterTest)

J2OBJC_FIELD_SETTER(ComKgalliganPartyclickerPresenterPartyListPresenterTest, dataProvider_, id<ComKgalliganPartyclickerDataDataProvider>)

FOUNDATION_EXPORT void ComKgalliganPartyclickerPresenterPartyListPresenterTest_init(ComKgalliganPartyclickerPresenterPartyListPresenterTest *self);

FOUNDATION_EXPORT ComKgalliganPartyclickerPresenterPartyListPresenterTest *new_ComKgalliganPartyclickerPresenterPartyListPresenterTest_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComKgalliganPartyclickerPresenterPartyListPresenterTest *create_ComKgalliganPartyclickerPresenterPartyListPresenterTest_init();

J2OBJC_TYPE_LITERAL_HEADER(ComKgalliganPartyclickerPresenterPartyListPresenterTest)

#endif

#pragma pop_macro("INCLUDE_ALL_ComKgalliganPartyclickerPresenterPartyListPresenterTest")
