//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "DaggerModule.h"
#include "DaggerProvides.h"
#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "PDDataProvider.h"
#include "PTMemoryDataProvider.h"
#include "PTTestNoContextModule.h"
#include "RxObservable.h"
#include "java/lang/annotation/Annotation.h"
#include "javax/inject/Singleton.h"

#pragma clang diagnostic ignored "-Wprotocol"

__attribute__((unused)) static IOSObjectArray *PTTestNoContextModule__Annotations$0();

__attribute__((unused)) static IOSObjectArray *PTTestNoContextModule__Annotations$1();

__attribute__((unused)) static IOSObjectArray *PTTestNoContextModule__Annotations$2();

@interface PTTestNoContextModule_$Lambda$1 : NSObject < RxObservable_Transformer >

- (id)callWithId:(id)o;

@end

J2OBJC_STATIC_INIT(PTTestNoContextModule_$Lambda$1)

inline PTTestNoContextModule_$Lambda$1 *PTTestNoContextModule_$Lambda$1_get_instance();
static PTTestNoContextModule_$Lambda$1 *PTTestNoContextModule_$Lambda$1_instance;
J2OBJC_STATIC_FIELD_OBJ_FINAL(PTTestNoContextModule_$Lambda$1, instance, PTTestNoContextModule_$Lambda$1 *)

__attribute__((unused)) static void PTTestNoContextModule_$Lambda$1_init(PTTestNoContextModule_$Lambda$1 *self);

__attribute__((unused)) static PTTestNoContextModule_$Lambda$1 *new_PTTestNoContextModule_$Lambda$1_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static PTTestNoContextModule_$Lambda$1 *create_PTTestNoContextModule_$Lambda$1_init();

@implementation PTTestNoContextModule

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  PTTestNoContextModule_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (id<PDDataProvider>)providesDataProvider {
  return create_PTMemoryDataProvider_init();
}

- (id<RxObservable_Transformer>)providesSchedulerTransformer {
  return JreLoadStatic(PTTestNoContextModule_$Lambda$1, instance);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LPDDataProvider;", 0x0, -1, -1, -1, -1, 0, -1 },
    { NULL, "LRxObservable_Transformer;", 0x0, -1, -1, -1, -1, 1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(providesDataProvider);
  methods[2].selector = @selector(providesSchedulerTransformer);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { (void *)&PTTestNoContextModule__Annotations$0, (void *)&PTTestNoContextModule__Annotations$1, (void *)&PTTestNoContextModule__Annotations$2 };
  static const J2ObjcClassInfo _PTTestNoContextModule = { "TestNoContextModule", "com.kgalligan.partyclicker.test", ptrTable, methods, NULL, 7, 0x1, 3, 0, -1, -1, -1, -1, 2 };
  return &_PTTestNoContextModule;
}

@end

void PTTestNoContextModule_init(PTTestNoContextModule *self) {
  NSObject_init(self);
}

PTTestNoContextModule *new_PTTestNoContextModule_init() {
  J2OBJC_NEW_IMPL(PTTestNoContextModule, init)
}

PTTestNoContextModule *create_PTTestNoContextModule_init() {
  J2OBJC_CREATE_IMPL(PTTestNoContextModule, init)
}

IOSObjectArray *PTTestNoContextModule__Annotations$0() {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_DaggerProvides(JreLoadEnum(DaggerProvides_Type, UNIQUE)), create_JavaxInjectSingleton() } count:2 type:JavaLangAnnotationAnnotation_class_()];
}

IOSObjectArray *PTTestNoContextModule__Annotations$1() {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_DaggerProvides(JreLoadEnum(DaggerProvides_Type, UNIQUE)), create_JavaxInjectSingleton() } count:2 type:JavaLangAnnotationAnnotation_class_()];
}

IOSObjectArray *PTTestNoContextModule__Annotations$2() {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_DaggerModule([IOSObjectArray arrayWithLength:0 type:IOSClass_class_()]) } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(PTTestNoContextModule)

J2OBJC_INITIALIZED_DEFN(PTTestNoContextModule_$Lambda$1)

@implementation PTTestNoContextModule_$Lambda$1

- (id)callWithId:(id)o {
  return (RxObservable *) cast_chk(o, [RxObservable class]);
}

+ (void)initialize {
  if (self == [PTTestNoContextModule_$Lambda$1 class]) {
    JreStrongAssignAndConsume(&PTTestNoContextModule_$Lambda$1_instance, new_PTTestNoContextModule_$Lambda$1_init());
    J2OBJC_SET_INITIALIZED(PTTestNoContextModule_$Lambda$1)
  }
}

@end

void PTTestNoContextModule_$Lambda$1_init(PTTestNoContextModule_$Lambda$1 *self) {
  NSObject_init(self);
}

PTTestNoContextModule_$Lambda$1 *new_PTTestNoContextModule_$Lambda$1_init() {
  J2OBJC_NEW_IMPL(PTTestNoContextModule_$Lambda$1, init)
}

PTTestNoContextModule_$Lambda$1 *create_PTTestNoContextModule_$Lambda$1_init() {
  J2OBJC_CREATE_IMPL(PTTestNoContextModule_$Lambda$1, init)
}
